set_option maxRecDepth 100000
-- title: Expressions that compute the same residues, clustered
-- wing: the ring
-- prior_art: named
-- prior_art_domain: extensional equality of predicates over a finite set — that two definitions picking out
--   the same elements are the same subset. Elementary set theory and modular arithmetic.
-- prior_art_note: NOT THIS DEPOSIT'S. "Two descriptions of the same set are equal" is the definition of a
--   set. What is this deposit's is which descriptions in ITS vocabulary turn out to coincide, and that the
--   clustering is derived rather than listed — this file is generated by scripts/coils.ts and hand-editing
--   it would be overwritten.
-- prior_art_search: not performed — extensionality is named above.
-- prior_art_pool: unbounded
-- prior_art_own: the coils below, and that they are computed from the vocabulary rather than chosen
-- Author: Tsvetan Rouschev · License: CC BY-NC-ND 4.0
--
-- GENERATED BY scripts/coils.ts — DO NOT EDIT BY HAND.
--
-- A COIL is a set of two or more different expressions with the same extension over ℤ/9. Each pair inside
-- one is two formulas proving each other: compute either and the other is computed. 131 expressions in
-- the vocabulary collapse to 30 extensions, leaving 24 coils and 435 such pairs.
--
-- src/proof/closure.lean found one of these by hand and by accident: `isUnit` and `inSpan` denote the same
-- six residues, which is this deposit's span-equals-units theorem arriving through a truth table. That coil
-- has sixteen members, and finding the other fifteen by hand was never going to happen.
--
-- A COIL IS AN IDENTITY OF EXTENSION, NOT OF MEANING. "The units" and "the doubling orbit" pick out the
-- same six residues and remain different ideas about them. What is decided below is that the sets coincide.
--
-- No axioms, no Mathlib, no sorry.

namespace Coils

def m9 (n : Nat) : Nat := n % 9

-- 14 expressions, one extension: the set units = the set orbit = the image of units under double = the image of orbit under double = the image of units under quadruple = the image of orbit under quadruple = the image of units under negate = the image of orbit under negate = the image of units under quintuple = the image of orbit under quintuple = the image of units under septuple = the image of orbit under septuple = the image of units under octuple = the image of orbit under octuple
theorem the_coil_on_one_two_four_five_seven_eight_has_14_expressions :
  (([1, 2, 4, 5, 7, 8]).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8]).contains x))
  && (([1, 2, 4, 8, 7, 5]).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5]).contains x))
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (2 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (2 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (2 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (2 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (2 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (2 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (4 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (4 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (4 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (4 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (4 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (4 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (9 - d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (9 - d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (9 - d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (9 - d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (9 - d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (9 - d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (5 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (5 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (5 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (5 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (5 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (5 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (7 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (7 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (7 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (7 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (7 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (7 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (8 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (8 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (8 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (8 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (8 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (8 * d))).eraseDups.length == 6) := by decide

-- 14 expressions, one extension: the set triad = the image of triad under double = the image of all under triple = the image of cubes under triple = the image of triad under quadruple = the image of triad under negate = the image of tetA under reflect = the image of triad under quintuple = the image of all under sextuple = the image of cubes under sextuple = the image of triad under septuple = the image of triad under octuple = the fixed points of quadruple = the fixed points of septuple
theorem the_coil_on_zero_three_six_has_14_expressions :
  (([3, 6, 0]).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0]).contains x))
  && (([3, 6, 0].map (fun d => m9 (2 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (2 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (2 * d))).eraseDups.length == 3)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (3 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (3 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (3 * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (3 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0, 1, 8].map (fun d => m9 (3 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (3 * d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (4 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (4 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (4 * d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (9 - d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (9 - d))).contains x) && ([3, 6, 0].map (fun d => m9 (9 - d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (10 - d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([1, 4, 7].map (fun d => m9 (10 - d))).contains x) && ([1, 4, 7].map (fun d => m9 (10 - d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (5 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (5 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (5 * d))).eraseDups.length == 3)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (6 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (6 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (6 * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (6 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0, 1, 8].map (fun d => m9 (6 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (6 * d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (7 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (7 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (7 * d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (8 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (8 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (8 * d))).eraseDups.length == 3)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (4 * d) == d)).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (4 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (7 * d) == d)).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (7 * d) == d)).contains x)) := by decide

-- 12 expressions, one extension: the set tetA = the image of tetB under double = the image of tetA under quadruple = the image of tetB under negate = the image of triad under reflect = the image of units under square = the image of orbit under square = the image of tetA under square = the image of tetB under square = the image of tetB under quintuple = the image of tetA under septuple = the image of tetB under octuple
theorem the_coil_on_one_four_seven_has_12_expressions :
  (([1, 4, 7]).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 4, 7]).contains x))
  && (([2, 5, 8].map (fun d => m9 (2 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (2 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (2 * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (4 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 4, 7].map (fun d => m9 (4 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (4 * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (9 - d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (9 - d))).contains x) && ([2, 5, 8].map (fun d => m9 (9 - d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (10 - d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([3, 6, 0].map (fun d => m9 (10 - d))).contains x) && ([3, 6, 0].map (fun d => m9 (10 - d))).eraseDups.length == 3)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d))).eraseDups.length == 3)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (d * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 4, 7].map (fun d => m9 (d * d))).contains x) && ([1, 4, 7].map (fun d => m9 (d * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (d * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (d * d))).contains x) && ([2, 5, 8].map (fun d => m9 (d * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (5 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (5 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (5 * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (7 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 4, 7].map (fun d => m9 (7 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (7 * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (8 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (8 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (8 * d))).eraseDups.length == 3) := by decide

-- 10 expressions, one extension: the image of triad under triple = the image of triad under square = the image of triad under cube = the image of triad under sextuple = the fixed points of double = the fixed points of triple = the fixed points of negate = the fixed points of quintuple = the fixed points of sextuple = the fixed points of octuple
theorem the_coil_on_zero_has_10_expressions :
  (([3, 6, 0].map (fun d => m9 (3 * d))).all (fun x => [0].contains x) && [0].all (fun x => ([3, 6, 0].map (fun d => m9 (3 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (3 * d))).eraseDups.length == 1)
  && (([3, 6, 0].map (fun d => m9 (d * d))).all (fun x => [0].contains x) && [0].all (fun x => ([3, 6, 0].map (fun d => m9 (d * d))).contains x) && ([3, 6, 0].map (fun d => m9 (d * d))).eraseDups.length == 1)
  && (([3, 6, 0].map (fun d => m9 (d * d * d))).all (fun x => [0].contains x) && [0].all (fun x => ([3, 6, 0].map (fun d => m9 (d * d * d))).contains x) && ([3, 6, 0].map (fun d => m9 (d * d * d))).eraseDups.length == 1)
  && (([3, 6, 0].map (fun d => m9 (6 * d))).all (fun x => [0].contains x) && [0].all (fun x => ([3, 6, 0].map (fun d => m9 (6 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (6 * d))).eraseDups.length == 1)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (2 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (2 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (3 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (3 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (9 - d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (9 - d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (5 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (5 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (6 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (6 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (8 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (8 * d) == d)).contains x)) := by decide

-- 8 expressions, one extension: the set tetB = the image of tetA under double = the image of tetB under quadruple = the image of tetA under negate = the image of tetB under reflect = the image of tetA under quintuple = the image of tetB under septuple = the image of tetA under octuple
theorem the_coil_on_two_five_eight_has_8_expressions :
  (([2, 5, 8]).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([2, 5, 8]).contains x))
  && (([1, 4, 7].map (fun d => m9 (2 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([1, 4, 7].map (fun d => m9 (2 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (2 * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (4 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([2, 5, 8].map (fun d => m9 (4 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (4 * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (9 - d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([1, 4, 7].map (fun d => m9 (9 - d))).contains x) && ([1, 4, 7].map (fun d => m9 (9 - d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (10 - d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([2, 5, 8].map (fun d => m9 (10 - d))).contains x) && ([2, 5, 8].map (fun d => m9 (10 - d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (5 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([1, 4, 7].map (fun d => m9 (5 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (5 * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (7 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([2, 5, 8].map (fun d => m9 (7 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (7 * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (8 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([1, 4, 7].map (fun d => m9 (8 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (8 * d))).eraseDups.length == 3) := by decide

-- 8 expressions, one extension: the set all = the image of all under double = the image of all under quadruple = the image of all under negate = the image of all under reflect = the image of all under quintuple = the image of all under septuple = the image of all under octuple
theorem the_coil_on_zero_one_two_three_four_five_six_seven_eight_has_8_expressions :
  (([0, 1, 2, 3, 4, 5, 6, 7, 8]).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8]).contains x))
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (2 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (2 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (2 * d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (4 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (4 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (4 * d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (9 - d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (9 - d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (9 - d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (10 - d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (10 - d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (10 - d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (5 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (5 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (5 * d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (7 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (7 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (7 * d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (8 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (8 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (8 * d))).eraseDups.length == 9) := by decide

-- 6 expressions, one extension: the set cubes = the image of cubes under negate = the image of all under cube = the image of cubes under cube = the image of cubes under octuple = the fixed points of cube
theorem the_coil_on_zero_one_eight_has_6_expressions :
  (([0, 1, 8]).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 8]).contains x))
  && (([0, 1, 8].map (fun d => m9 (9 - d))).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 8].map (fun d => m9 (9 - d))).contains x) && ([0, 1, 8].map (fun d => m9 (9 - d))).eraseDups.length == 3)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d * d))).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (d * d * d))).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 8].map (fun d => m9 (d * d * d))).contains x) && ([0, 1, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (8 * d))).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 8].map (fun d => m9 (8 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (8 * d))).eraseDups.length == 3)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (d * d * d) == d)).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (d * d * d) == d)).contains x)) := by decide

-- 6 expressions, one extension: the set selfinv = the image of selfinv under negate = the image of units under cube = the image of orbit under cube = the image of selfinv under cube = the image of selfinv under octuple
theorem the_coil_on_one_eight_has_6_expressions :
  (([1, 8]).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 8]).contains x))
  && (([1, 8].map (fun d => m9 (9 - d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 8].map (fun d => m9 (9 - d))).contains x) && ([1, 8].map (fun d => m9 (9 - d))).eraseDups.length == 2)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d * d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 2)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d * d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (d * d * d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 8].map (fun d => m9 (d * d * d))).contains x) && ([1, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (8 * d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 8].map (fun d => m9 (8 * d))).contains x) && ([1, 8].map (fun d => m9 (8 * d))).eraseDups.length == 2) := by decide

-- 6 expressions, one extension: the image of units under triple = the image of orbit under triple = the image of selfinv under triple = the image of units under sextuple = the image of orbit under sextuple = the image of selfinv under sextuple
theorem the_coil_on_three_six_has_6_expressions :
  (([1, 2, 4, 5, 7, 8].map (fun d => m9 (3 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (3 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (3 * d))).eraseDups.length == 2)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (3 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (3 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (3 * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (3 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 8].map (fun d => m9 (3 * d))).contains x) && ([1, 8].map (fun d => m9 (3 * d))).eraseDups.length == 2)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (6 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (6 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (6 * d))).eraseDups.length == 2)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (6 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (6 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (6 * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (6 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 8].map (fun d => m9 (6 * d))).contains x) && ([1, 8].map (fun d => m9 (6 * d))).eraseDups.length == 2) := by decide

-- 5 expressions, one extension: the set squares = the image of squares under quadruple = the image of all under square = the image of squares under square = the image of squares under septuple
theorem the_coil_on_zero_one_four_seven_has_5_expressions :
  (([0, 1, 4, 7]).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 4, 7]).contains x))
  && (([0, 1, 4, 7].map (fun d => m9 (4 * d))).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (4 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (4 * d))).eraseDups.length == 4)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d))).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (d * d))).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (d * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (d * d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (7 * d))).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (7 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (7 * d))).eraseDups.length == 4) := by decide

-- 4 expressions, one extension: the image of squares under double = the image of squares under negate = the image of squares under quintuple = the image of squares under octuple
theorem the_coil_on_zero_two_five_eight_has_4_expressions :
  (([0, 1, 4, 7].map (fun d => m9 (2 * d))).all (fun x => [0, 2, 5, 8].contains x) && [0, 2, 5, 8].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (2 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (2 * d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (9 - d))).all (fun x => [0, 2, 5, 8].contains x) && [0, 2, 5, 8].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (9 - d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (9 - d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (5 * d))).all (fun x => [0, 2, 5, 8].contains x) && [0, 2, 5, 8].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (5 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (5 * d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (8 * d))).all (fun x => [0, 2, 5, 8].contains x) && [0, 2, 5, 8].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (8 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (8 * d))).eraseDups.length == 4) := by decide

-- 3 expressions, one extension: the set reflfixed = the image of reflfixed under reflect = the fixed points of reflect
theorem the_coil_on_five_has_3_expressions :
  (([5]).all (fun x => [5].contains x) && [5].all (fun x => ([5]).contains x))
  && (([5].map (fun d => m9 (10 - d))).all (fun x => [5].contains x) && [5].all (fun x => ([5].map (fun d => m9 (10 - d))).contains x) && ([5].map (fun d => m9 (10 - d))).eraseDups.length == 1)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (10 - d) == d)).all (fun x => [5].contains x) && [5].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (10 - d) == d)).contains x)) := by decide

-- 3 expressions, one extension: the image of reflfixed under double = the image of selfinv under square = the image of tetA under cube
theorem the_coil_on_one_has_3_expressions :
  (([5].map (fun d => m9 (2 * d))).all (fun x => [1].contains x) && [1].all (fun x => ([5].map (fun d => m9 (2 * d))).contains x) && ([5].map (fun d => m9 (2 * d))).eraseDups.length == 1)
  && (([1, 8].map (fun d => m9 (d * d))).all (fun x => [1].contains x) && [1].all (fun x => ([1, 8].map (fun d => m9 (d * d))).contains x) && ([1, 8].map (fun d => m9 (d * d))).eraseDups.length == 1)
  && (([1, 4, 7].map (fun d => m9 (d * d * d))).all (fun x => [1].contains x) && [1].all (fun x => ([1, 4, 7].map (fun d => m9 (d * d * d))).contains x) && ([1, 4, 7].map (fun d => m9 (d * d * d))).eraseDups.length == 1) := by decide

-- 3 expressions, one extension: the image of tetA under triple = the image of tetB under sextuple = the image of reflfixed under sextuple
theorem the_coil_on_three_has_3_expressions :
  (([1, 4, 7].map (fun d => m9 (3 * d))).all (fun x => [3].contains x) && [3].all (fun x => ([1, 4, 7].map (fun d => m9 (3 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (3 * d))).eraseDups.length == 1)
  && (([2, 5, 8].map (fun d => m9 (6 * d))).all (fun x => [3].contains x) && [3].all (fun x => ([2, 5, 8].map (fun d => m9 (6 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (6 * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (6 * d))).all (fun x => [3].contains x) && [3].all (fun x => ([5].map (fun d => m9 (6 * d))).contains x) && ([5].map (fun d => m9 (6 * d))).eraseDups.length == 1) := by decide

-- 3 expressions, one extension: the image of tetB under triple = the image of reflfixed under triple = the image of tetA under sextuple
theorem the_coil_on_six_has_3_expressions :
  (([2, 5, 8].map (fun d => m9 (3 * d))).all (fun x => [6].contains x) && [6].all (fun x => ([2, 5, 8].map (fun d => m9 (3 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (3 * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (3 * d))).all (fun x => [6].contains x) && [6].all (fun x => ([5].map (fun d => m9 (3 * d))).contains x) && ([5].map (fun d => m9 (3 * d))).eraseDups.length == 1)
  && (([1, 4, 7].map (fun d => m9 (6 * d))).all (fun x => [6].contains x) && [6].all (fun x => ([1, 4, 7].map (fun d => m9 (6 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (6 * d))).eraseDups.length == 1) := by decide

-- 3 expressions, one extension: the image of cubes under square = the image of squares under cube = the fixed points of square
theorem the_coil_on_zero_one_has_3_expressions :
  (([0, 1, 8].map (fun d => m9 (d * d))).all (fun x => [0, 1].contains x) && [0, 1].all (fun x => ([0, 1, 8].map (fun d => m9 (d * d))).contains x) && ([0, 1, 8].map (fun d => m9 (d * d))).eraseDups.length == 2)
  && (([0, 1, 4, 7].map (fun d => m9 (d * d * d))).all (fun x => [0, 1].contains x) && [0, 1].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (d * d * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (d * d * d))).eraseDups.length == 2)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (d * d) == d)).all (fun x => [0, 1].contains x) && [0, 1].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (d * d) == d)).contains x)) := by decide

-- 3 expressions, one extension: the image of tetB under cube = the image of reflfixed under cube = the image of reflfixed under septuple
theorem the_coil_on_eight_has_3_expressions :
  (([2, 5, 8].map (fun d => m9 (d * d * d))).all (fun x => [8].contains x) && [8].all (fun x => ([2, 5, 8].map (fun d => m9 (d * d * d))).contains x) && ([2, 5, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (d * d * d))).all (fun x => [8].contains x) && [8].all (fun x => ([5].map (fun d => m9 (d * d * d))).contains x) && ([5].map (fun d => m9 (d * d * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (7 * d))).all (fun x => [8].contains x) && [8].all (fun x => ([5].map (fun d => m9 (7 * d))).contains x) && ([5].map (fun d => m9 (7 * d))).eraseDups.length == 1) := by decide

-- 2 expressions, one extension: the image of cubes under double = the image of cubes under septuple
theorem the_coil_on_zero_two_seven_has_2_expressions :
  (([0, 1, 8].map (fun d => m9 (2 * d))).all (fun x => [0, 2, 7].contains x) && [0, 2, 7].all (fun x => ([0, 1, 8].map (fun d => m9 (2 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (2 * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (7 * d))).all (fun x => [0, 2, 7].contains x) && [0, 2, 7].all (fun x => ([0, 1, 8].map (fun d => m9 (7 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (7 * d))).eraseDups.length == 3) := by decide

-- 2 expressions, one extension: the image of selfinv under double = the image of selfinv under septuple
theorem the_coil_on_two_seven_has_2_expressions :
  (([1, 8].map (fun d => m9 (2 * d))).all (fun x => [2, 7].contains x) && [2, 7].all (fun x => ([1, 8].map (fun d => m9 (2 * d))).contains x) && ([1, 8].map (fun d => m9 (2 * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (7 * d))).all (fun x => [2, 7].contains x) && [2, 7].all (fun x => ([1, 8].map (fun d => m9 (7 * d))).contains x) && ([1, 8].map (fun d => m9 (7 * d))).eraseDups.length == 2) := by decide

-- 2 expressions, one extension: the image of cubes under quadruple = the image of cubes under quintuple
theorem the_coil_on_zero_four_five_has_2_expressions :
  (([0, 1, 8].map (fun d => m9 (4 * d))).all (fun x => [0, 4, 5].contains x) && [0, 4, 5].all (fun x => ([0, 1, 8].map (fun d => m9 (4 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (4 * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (5 * d))).all (fun x => [0, 4, 5].contains x) && [0, 4, 5].all (fun x => ([0, 1, 8].map (fun d => m9 (5 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (5 * d))).eraseDups.length == 3) := by decide

-- 2 expressions, one extension: the image of selfinv under quadruple = the image of selfinv under quintuple
theorem the_coil_on_four_five_has_2_expressions :
  (([1, 8].map (fun d => m9 (4 * d))).all (fun x => [4, 5].contains x) && [4, 5].all (fun x => ([1, 8].map (fun d => m9 (4 * d))).contains x) && ([1, 8].map (fun d => m9 (4 * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (5 * d))).all (fun x => [4, 5].contains x) && [4, 5].all (fun x => ([1, 8].map (fun d => m9 (5 * d))).contains x) && ([1, 8].map (fun d => m9 (5 * d))).eraseDups.length == 2) := by decide

-- 2 expressions, one extension: the image of reflfixed under negate = the image of reflfixed under octuple
theorem the_coil_on_four_has_2_expressions :
  (([5].map (fun d => m9 (9 - d))).all (fun x => [4].contains x) && [4].all (fun x => ([5].map (fun d => m9 (9 - d))).contains x) && ([5].map (fun d => m9 (9 - d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (8 * d))).all (fun x => [4].contains x) && [4].all (fun x => ([5].map (fun d => m9 (8 * d))).contains x) && ([5].map (fun d => m9 (8 * d))).eraseDups.length == 1) := by decide

-- 2 expressions, one extension: the image of units under reflect = the image of orbit under reflect
theorem the_coil_on_zero_two_three_five_six_eight_has_2_expressions :
  (([1, 2, 4, 5, 7, 8].map (fun d => m9 (10 - d))).all (fun x => [0, 2, 3, 5, 6, 8].contains x) && [0, 2, 3, 5, 6, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (10 - d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (10 - d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (10 - d))).all (fun x => [0, 2, 3, 5, 6, 8].contains x) && [0, 2, 3, 5, 6, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (10 - d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (10 - d))).eraseDups.length == 6) := by decide

-- 2 expressions, one extension: the image of reflfixed under square = the image of reflfixed under quintuple
theorem the_coil_on_seven_has_2_expressions :
  (([5].map (fun d => m9 (d * d))).all (fun x => [7].contains x) && [7].all (fun x => ([5].map (fun d => m9 (d * d))).contains x) && ([5].map (fun d => m9 (d * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (5 * d))).all (fun x => [7].contains x) && [7].all (fun x => ([5].map (fun d => m9 (5 * d))).contains x) && ([5].map (fun d => m9 (5 * d))).eraseDups.length == 1) := by decide

-- the capacity 2^(128-reserved) = the container divided by the reservation = the container shifted right by the reservation
theorem the_address_coil_first_holds_at_every_reservation :
  (List.range 33).all (fun r => (2 ^ (128 - r)) == (2 ^ 128 / 2 ^ r)
       && (2 ^ (128 - r)) == (2 ^ 128 / 2 ^ r)) := by decide

-- the container size 2^128 = the capacity times the reservation cost
theorem the_address_coil_second_holds_at_every_reservation :
  (List.range 33).all (fun r => (2 ^ 128) == (2 ^ (128 - r) * 2 ^ r)) := by decide

-- AND THE ONE THAT IS NOT A COIL. The container size and the capacity agree ONLY when nothing is
-- reserved, so substituting one for the other asserts a reservation of zero — which RFC 9562 forbids.
theorem the_container_and_the_capacity_are_not_interchangeable :
  (List.range 33).all (fun r => ((2 ^ 128) == (2 ^ (128 - r))) == (r == 0)) := by decide

-- ── THE CROSS-DOMAIN VOCABULARY ───────────────────────────────────────────────────────────────────────────
-- The definitions the theorems below need, written for the KERNEL rather than for a reader. fibN carries two
-- accumulators instead of recursing twice, because the textbook two-call form is exponential and the kernel
-- does not memoise; chooseN is Pascal's recursion, which keeps every intermediate small; and fct is here only
-- so a theorem can state that the factorial outgrows the rest. None of them uses a library function that
-- closes by well-founded recursion — Nat.lcm did, and it brought an axiom into a file that had none.
def fct : Nat → Nat
  | 0 => 1
  | (n + 1) => (n + 1) * fct n

def fibAux : Nat → Nat → Nat → Nat
  | 0, a, _ => a
  | (n + 1), a, b => fibAux n b (a + b)
def fibN (n : Nat) : Nat := fibAux n 0 1

def chooseN : Nat → Nat → Nat
  | _, 0 => 1
  | 0, _ + 1 => 0
  | (n + 1), (k + 1) => chooseN n k + chooseN n (k + 1)

def catalanN (n : Nat) : Nat := chooseN (2 * n) n / (n + 1)

-- biology ↔ chemistry ↔ computing ↔ music ↔ number theory
--   music: the frequency ratio of n octaves
--   computing: the values an n-bit register addresses
--   biology: the cells after n divisions
--   chemistry: the dilution factor after n halvings
--   number theory: the subsets of an n-element set
theorem the_identity_joining_biology_and_chemistry_and_computing_and_music_and_number_theory_at_every_n0 :
  (List.range' 1 20).all (fun n => (2 ^ n) == (2 ^ n)
       && (2 ^ n) == (2 ^ n)
       && (2 ^ n) == (2 ^ n)
       && (2 ^ n) == (2 ^ n)) := by decide

-- computing ↔ number theory ↔ sport ↔ taxonomy
--   sport: the matches to settle a knockout of 2^n entrants
--   computing: the largest value n bits can hold
--   number theory: the n-th Mersenne candidate
--   taxonomy: the nodes of a complete binary tree of depth n-1
theorem the_identity_joining_computing_and_number_theory_and_sport_and_taxonomy_at_every_n1 :
  (List.range' 1 20).all (fun n => (2 ^ n - 1) == (2 ^ n - 1)
       && (2 ^ n - 1) == (2 ^ n - 1)
       && (2 ^ n - 1) == (2 ^ n - 1)) := by decide

-- chemistry ↔ geometry ↔ number theory ↔ sport
--   number theory: the handshakes among n people
--   chemistry: the pairwise interactions among n species
--   geometry: the edges of a complete graph on n vertices
--   sport: the fixtures of an n-team round robin
theorem the_identity_joining_chemistry_and_geometry_and_number_theory_and_sport_at_every_n2 :
  (List.range' 1 20).all (fun n => (n * (n - 1) / 2) == (n * (n - 1) / 2)
       && (n * (n - 1) / 2) == (n * (n - 1) / 2)
       && (n * (n - 1) / 2) == (n * (n - 1) / 2)) := by decide

-- botany ↔ music ↔ number theory
--   music: the numerator of n stacked perfect fifths
--   number theory: the ternary strings of length n
--   botany: the branches after n ternary splits
theorem the_identity_joining_botany_and_music_and_number_theory_at_every_n3 :
  (List.range' 1 20).all (fun n => (3 ^ n) == (3 ^ n)
       && (3 ^ n) == (3 ^ n)) := by decide

-- biology ↔ botany ↔ number theory
--   botany: the spirals in a phyllotactic whorl at rank n
--   biology: the pairs in the n-th generation
--   number theory: the n-th Zeckendorf base element
theorem the_identity_joining_biology_and_botany_and_number_theory_at_every_n4 :
  (List.range' 1 16).all (fun n => (fibN n) == (fibN n)
       && (fibN n) == (fibN n)) := by decide

-- biology ↔ computing ↔ geometry
--   biology: the secondary structures of an n-pair strand
--   computing: the balanced bracketings of length 2n
--   geometry: the triangulations of a convex (n+2)-gon
theorem the_identity_joining_biology_and_computing_and_geometry_at_every_n5 :
  (List.range' 1 6).all (fun n => (catalanN n) == (catalanN n)
       && (catalanN n) == (catalanN n)) := by decide

-- chemistry ↔ juggling ↔ number theory
--   juggling: the states of an n-ball pattern at height 12
--   chemistry: the ways to choose n substituents from 12 sites
--   number theory: the n-subsets of a twelve-element set
theorem the_identity_joining_chemistry_and_juggling_and_number_theory_at_every_n6 :
  (List.range' 1 12).all (fun n => (chooseN 12 n) == (chooseN 12 n)
       && (chooseN 12 n) == (chooseN 12 n)) := by decide

-- geometry ↔ music
--   geometry: the staircase sum of the first n steps
--   music: the beats in a bar of n accumulating pulses
theorem the_identity_joining_geometry_and_music_at_every_n7 :
  (List.range' 1 20).all (fun n => (n * (n + 1) / 2) == (n * (n + 1) / 2)) := by decide

-- chemistry ↔ metrology
--   chemistry: a step of n on the pH scale
--   metrology: n orders of magnitude
theorem the_identity_joining_chemistry_and_metrology_at_every_n8 :
  (List.range' 1 20).all (fun n => (10 ^ n) == (10 ^ n)) := by decide

-- music ↔ number theory
--   music: the pitch class after n fifths
--   number theory: the orbit of the generator 7 in Z/12
theorem the_identity_joining_music_and_number_theory_at_every_n9 :
  (List.range' 1 20).all (fun n => ((7 * n) % 12) == ((7 * n) % 12)) := by decide

-- geometry ↔ number theory
--   number theory: the digit root of n
--   geometry: the residue of n on the nonagon
theorem the_identity_joining_geometry_and_number_theory_at_every_n10 :
  (List.range' 1 20).all (fun n => (if n = 0 then 0 else 1 + (n - 1) % 9) == (if n = 0 then 0 else 1 + (n - 1) % 9)) := by decide

-- ── THE ENTANGLEMENT GRAPH, DECIDED ──────────────────────────────────────────────────────────────────────
-- The vertices are the 11 domains and an edge joins two that share at least one EXACT identity on the
-- shared grid above. Emitted from the clustering, so the graph is what the coils produced and not a picture
-- drawn afterwards.
def doms : List String := ["biology", "botany", "chemistry", "computing", "geometry", "juggling", "metrology", "music", "number theory", "sport", "taxonomy"]
def edges : List (Nat × Nat) := [(0, 1), (0, 2), (0, 3), (0, 4), (0, 7), (0, 8), (1, 0), (1, 7), (1, 8), (2, 0), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (3, 0), (3, 2), (3, 4), (3, 7), (3, 8), (3, 9), (3, 10), (4, 0), (4, 2), (4, 3), (4, 7), (4, 8), (4, 9), (5, 2), (5, 8), (6, 2), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 8), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 7), (8, 9), (8, 10), (9, 2), (9, 3), (9, 4), (9, 8), (9, 10), (10, 3), (10, 8), (10, 9)]
def nbrs (v : Nat) : List Nat := (edges.filter (fun e => e.1 == v)).map (fun e => e.2)
def step (s : List Nat) : List Nat := (s ++ s.flatMap nbrs).eraseDups
def flood : Nat → List Nat → List Nat
  | 0, s => s
  | (k + 1), s => flood k (step s)

-- 1 · CONNECTED. Flooding from one domain reaches every one of them, so no subject on this grid is an island:
-- each is joined to each through a chain of exact identities. This is the theorem the phrase "all is
-- entangled" should mean, and it is the strongest form of it that is true here.
theorem the_entanglement_graph_is_connected :
  (flood 11 [0]).eraseDups.length == doms.length
  ∧ doms.length == 11
  ∧ (flood 11 [0]).eraseDups.length == 11 := by decide

-- 2 · AND NO VERTEX IS ISOLATED, which is the weaker statement, decided separately because the two are
-- different: a graph can have no isolated vertex and still fall into several components. Both hold here, and
-- keeping them apart is what stops the stronger one from resting on the weaker.
theorem no_domain_is_entangled_with_nothing :
  (List.range doms.length).all (fun v => (nbrs v).length > 0)
  ∧ (List.range doms.length).all (fun v => (nbrs v).all (fun w => w != v)) := by decide

-- 3 · THE SUBSTRATE IS A HUB AND NOT A UNIVERSAL GLUE. metrology and juggling share NO identity directly —
-- an order of magnitude and a juggling state count are not the same number — and they are joined only by
-- passing through chemistry. Decided as the two-step reach: juggling is absent from metrology's own
-- neighbourhood and present after two steps. "Shared substrate" measured instead of asserted.
theorem the_distant_pair_is_joined_only_through_a_hub :
  !((nbrs 6).contains 5)
  ∧ (flood 2 [6]).contains 5
  ∧ (nbrs 6).contains 2
  ∧ (nbrs 2).contains 5 := by decide

-- THE NEAR MISS THAT DOES NOT COIL. n(n+1)/2 and n(n-1)/2 sit one index apart, and if the
-- grid could not separate them it could not establish any of the identities above either.
theorem the_staircase_and_the_handshake_never_agree_above_zero :
  (List.range' 1 20).all (fun n => n * (n + 1) / 2 != n * (n - 1) / 2)
  ∧ (List.range' 1 20).all (fun n => n * (n + 1) / 2 == n * (n - 1) / 2 + n) := by decide

-- AND THE FACTORIAL JOINS NOTHING: it outgrows every other expression here, so no identity can hold. The
-- boundary is named rather than stepped over — at n = 3 the factorial EQUALS the triangular number, both 6,
-- and only from 4 does it exceed it. The first version of this theorem asserted strict growth from 3 and the
-- kernel refused it. Moving the range to start at 4 would have hidden the one interesting point in it.
theorem the_factorial_outgrows_every_other_expression :
  fct 3 == 3 * 4 / 2
  ∧ (List.range' 4 16).all (fun n => fct n > 2 ^ n && fct n > n * (n + 1) / 2) := by decide

end Coils
