set_option maxRecDepth 100000
-- title: Expressions that compute the same residues, clustered
-- wing: the ring
-- prior_art: named
-- prior_art_domain: extensional equality of predicates over a finite set — that two definitions picking out
--   the same elements are the same subset. Elementary set theory and modular arithmetic.
-- prior_art_note: NOT THIS DEPOSIT'S. "Two descriptions of the same set are equal" is the definition of a
--   set. What is this deposit's is which descriptions in ITS vocabulary turn out to coincide, and that the
--   clustering is derived rather than listed — this file is generated by scripts/coils.ts and hand-editing
--   it would be overwritten.
-- prior_art_search: not performed — extensionality is named above.
-- prior_art_pool: unbounded
-- prior_art_own: the coils below, and that they are computed from the vocabulary rather than chosen
-- Author: Tsvetan Rouschev · License: CC BY-NC-ND 4.0
--
-- GENERATED BY scripts/coils.ts — DO NOT EDIT BY HAND.
--
-- A COIL is a set of two or more different expressions with the same extension over ℤ/9. Each pair inside
-- one is two formulas proving each other: compute either and the other is computed. 131 expressions in
-- the vocabulary collapse to 30 extensions, leaving 24 coils and 435 such pairs.
--
-- src/proof/closure.lean found one of these by hand and by accident: `isUnit` and `inSpan` denote the same
-- six residues, which is this deposit's span-equals-units theorem arriving through a truth table. That coil
-- has sixteen members, and finding the other fifteen by hand was never going to happen.
--
-- A COIL IS AN IDENTITY OF EXTENSION, NOT OF MEANING. "The units" and "the doubling orbit" pick out the
-- same six residues and remain different ideas about them. What is decided below is that the sets coincide.
--
-- No axioms, no Mathlib, no sorry.

namespace Coils

def m9 (n : Nat) : Nat := n % 9

-- 14 expressions, one extension: the set units = the set orbit = the image of units under double = the image of orbit under double = the image of units under quadruple = the image of orbit under quadruple = the image of units under negate = the image of orbit under negate = the image of units under quintuple = the image of orbit under quintuple = the image of units under septuple = the image of orbit under septuple = the image of units under octuple = the image of orbit under octuple
theorem the_coil_on_one_two_four_five_seven_eight_has_14_expressions :
  (([1, 2, 4, 5, 7, 8]).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8]).contains x))
  && (([1, 2, 4, 8, 7, 5]).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5]).contains x))
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (2 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (2 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (2 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (2 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (2 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (2 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (4 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (4 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (4 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (4 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (4 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (4 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (9 - d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (9 - d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (9 - d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (9 - d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (9 - d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (9 - d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (5 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (5 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (5 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (5 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (5 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (5 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (7 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (7 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (7 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (7 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (7 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (7 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (8 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (8 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (8 * d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (8 * d))).all (fun x => [1, 2, 4, 5, 7, 8].contains x) && [1, 2, 4, 5, 7, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (8 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (8 * d))).eraseDups.length == 6) := by decide

-- 14 expressions, one extension: the set triad = the image of triad under double = the image of all under triple = the image of cubes under triple = the image of triad under quadruple = the image of triad under negate = the image of tetA under reflect = the image of triad under quintuple = the image of all under sextuple = the image of cubes under sextuple = the image of triad under septuple = the image of triad under octuple = the fixed points of quadruple = the fixed points of septuple
theorem the_coil_on_zero_three_six_has_14_expressions :
  (([3, 6, 0]).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0]).contains x))
  && (([3, 6, 0].map (fun d => m9 (2 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (2 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (2 * d))).eraseDups.length == 3)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (3 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (3 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (3 * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (3 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0, 1, 8].map (fun d => m9 (3 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (3 * d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (4 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (4 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (4 * d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (9 - d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (9 - d))).contains x) && ([3, 6, 0].map (fun d => m9 (9 - d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (10 - d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([1, 4, 7].map (fun d => m9 (10 - d))).contains x) && ([1, 4, 7].map (fun d => m9 (10 - d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (5 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (5 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (5 * d))).eraseDups.length == 3)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (6 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (6 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (6 * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (6 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0, 1, 8].map (fun d => m9 (6 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (6 * d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (7 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (7 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (7 * d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (8 * d))).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([3, 6, 0].map (fun d => m9 (8 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (8 * d))).eraseDups.length == 3)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (4 * d) == d)).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (4 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (7 * d) == d)).all (fun x => [0, 3, 6].contains x) && [0, 3, 6].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (7 * d) == d)).contains x)) := by decide

-- 12 expressions, one extension: the set tetA = the image of tetB under double = the image of tetA under quadruple = the image of tetB under negate = the image of triad under reflect = the image of units under square = the image of orbit under square = the image of tetA under square = the image of tetB under square = the image of tetB under quintuple = the image of tetA under septuple = the image of tetB under octuple
theorem the_coil_on_one_four_seven_has_12_expressions :
  (([1, 4, 7]).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 4, 7]).contains x))
  && (([2, 5, 8].map (fun d => m9 (2 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (2 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (2 * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (4 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 4, 7].map (fun d => m9 (4 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (4 * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (9 - d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (9 - d))).contains x) && ([2, 5, 8].map (fun d => m9 (9 - d))).eraseDups.length == 3)
  && (([3, 6, 0].map (fun d => m9 (10 - d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([3, 6, 0].map (fun d => m9 (10 - d))).contains x) && ([3, 6, 0].map (fun d => m9 (10 - d))).eraseDups.length == 3)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d))).eraseDups.length == 3)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (d * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 4, 7].map (fun d => m9 (d * d))).contains x) && ([1, 4, 7].map (fun d => m9 (d * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (d * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (d * d))).contains x) && ([2, 5, 8].map (fun d => m9 (d * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (5 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (5 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (5 * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (7 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([1, 4, 7].map (fun d => m9 (7 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (7 * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (8 * d))).all (fun x => [1, 4, 7].contains x) && [1, 4, 7].all (fun x => ([2, 5, 8].map (fun d => m9 (8 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (8 * d))).eraseDups.length == 3) := by decide

-- 10 expressions, one extension: the image of triad under triple = the image of triad under square = the image of triad under cube = the image of triad under sextuple = the fixed points of double = the fixed points of triple = the fixed points of negate = the fixed points of quintuple = the fixed points of sextuple = the fixed points of octuple
theorem the_coil_on_zero_has_10_expressions :
  (([3, 6, 0].map (fun d => m9 (3 * d))).all (fun x => [0].contains x) && [0].all (fun x => ([3, 6, 0].map (fun d => m9 (3 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (3 * d))).eraseDups.length == 1)
  && (([3, 6, 0].map (fun d => m9 (d * d))).all (fun x => [0].contains x) && [0].all (fun x => ([3, 6, 0].map (fun d => m9 (d * d))).contains x) && ([3, 6, 0].map (fun d => m9 (d * d))).eraseDups.length == 1)
  && (([3, 6, 0].map (fun d => m9 (d * d * d))).all (fun x => [0].contains x) && [0].all (fun x => ([3, 6, 0].map (fun d => m9 (d * d * d))).contains x) && ([3, 6, 0].map (fun d => m9 (d * d * d))).eraseDups.length == 1)
  && (([3, 6, 0].map (fun d => m9 (6 * d))).all (fun x => [0].contains x) && [0].all (fun x => ([3, 6, 0].map (fun d => m9 (6 * d))).contains x) && ([3, 6, 0].map (fun d => m9 (6 * d))).eraseDups.length == 1)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (2 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (2 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (3 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (3 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (9 - d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (9 - d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (5 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (5 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (6 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (6 * d) == d)).contains x))
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (8 * d) == d)).all (fun x => [0].contains x) && [0].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (8 * d) == d)).contains x)) := by decide

-- 8 expressions, one extension: the set tetB = the image of tetA under double = the image of tetB under quadruple = the image of tetA under negate = the image of tetB under reflect = the image of tetA under quintuple = the image of tetB under septuple = the image of tetA under octuple
theorem the_coil_on_two_five_eight_has_8_expressions :
  (([2, 5, 8]).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([2, 5, 8]).contains x))
  && (([1, 4, 7].map (fun d => m9 (2 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([1, 4, 7].map (fun d => m9 (2 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (2 * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (4 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([2, 5, 8].map (fun d => m9 (4 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (4 * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (9 - d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([1, 4, 7].map (fun d => m9 (9 - d))).contains x) && ([1, 4, 7].map (fun d => m9 (9 - d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (10 - d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([2, 5, 8].map (fun d => m9 (10 - d))).contains x) && ([2, 5, 8].map (fun d => m9 (10 - d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (5 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([1, 4, 7].map (fun d => m9 (5 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (5 * d))).eraseDups.length == 3)
  && (([2, 5, 8].map (fun d => m9 (7 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([2, 5, 8].map (fun d => m9 (7 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (7 * d))).eraseDups.length == 3)
  && (([1, 4, 7].map (fun d => m9 (8 * d))).all (fun x => [2, 5, 8].contains x) && [2, 5, 8].all (fun x => ([1, 4, 7].map (fun d => m9 (8 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (8 * d))).eraseDups.length == 3) := by decide

-- 8 expressions, one extension: the set all = the image of all under double = the image of all under quadruple = the image of all under negate = the image of all under reflect = the image of all under quintuple = the image of all under septuple = the image of all under octuple
theorem the_coil_on_zero_one_two_three_four_five_six_seven_eight_has_8_expressions :
  (([0, 1, 2, 3, 4, 5, 6, 7, 8]).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8]).contains x))
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (2 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (2 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (2 * d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (4 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (4 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (4 * d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (9 - d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (9 - d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (9 - d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (10 - d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (10 - d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (10 - d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (5 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (5 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (5 * d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (7 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (7 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (7 * d))).eraseDups.length == 9)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (8 * d))).all (fun x => [0, 1, 2, 3, 4, 5, 6, 7, 8].contains x) && [0, 1, 2, 3, 4, 5, 6, 7, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (8 * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (8 * d))).eraseDups.length == 9) := by decide

-- 6 expressions, one extension: the set cubes = the image of cubes under negate = the image of all under cube = the image of cubes under cube = the image of cubes under octuple = the fixed points of cube
theorem the_coil_on_zero_one_eight_has_6_expressions :
  (([0, 1, 8]).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 8]).contains x))
  && (([0, 1, 8].map (fun d => m9 (9 - d))).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 8].map (fun d => m9 (9 - d))).contains x) && ([0, 1, 8].map (fun d => m9 (9 - d))).eraseDups.length == 3)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d * d))).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (d * d * d))).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 8].map (fun d => m9 (d * d * d))).contains x) && ([0, 1, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (8 * d))).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0, 1, 8].map (fun d => m9 (8 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (8 * d))).eraseDups.length == 3)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (d * d * d) == d)).all (fun x => [0, 1, 8].contains x) && [0, 1, 8].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (d * d * d) == d)).contains x)) := by decide

-- 6 expressions, one extension: the set selfinv = the image of selfinv under negate = the image of units under cube = the image of orbit under cube = the image of selfinv under cube = the image of selfinv under octuple
theorem the_coil_on_one_eight_has_6_expressions :
  (([1, 8]).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 8]).contains x))
  && (([1, 8].map (fun d => m9 (9 - d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 8].map (fun d => m9 (9 - d))).contains x) && ([1, 8].map (fun d => m9 (9 - d))).eraseDups.length == 2)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d * d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 2)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d * d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (d * d * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (d * d * d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 8].map (fun d => m9 (d * d * d))).contains x) && ([1, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (8 * d))).all (fun x => [1, 8].contains x) && [1, 8].all (fun x => ([1, 8].map (fun d => m9 (8 * d))).contains x) && ([1, 8].map (fun d => m9 (8 * d))).eraseDups.length == 2) := by decide

-- 6 expressions, one extension: the image of units under triple = the image of orbit under triple = the image of selfinv under triple = the image of units under sextuple = the image of orbit under sextuple = the image of selfinv under sextuple
theorem the_coil_on_three_six_has_6_expressions :
  (([1, 2, 4, 5, 7, 8].map (fun d => m9 (3 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (3 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (3 * d))).eraseDups.length == 2)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (3 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (3 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (3 * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (3 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 8].map (fun d => m9 (3 * d))).contains x) && ([1, 8].map (fun d => m9 (3 * d))).eraseDups.length == 2)
  && (([1, 2, 4, 5, 7, 8].map (fun d => m9 (6 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (6 * d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (6 * d))).eraseDups.length == 2)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (6 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (6 * d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (6 * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (6 * d))).all (fun x => [3, 6].contains x) && [3, 6].all (fun x => ([1, 8].map (fun d => m9 (6 * d))).contains x) && ([1, 8].map (fun d => m9 (6 * d))).eraseDups.length == 2) := by decide

-- 5 expressions, one extension: the set squares = the image of squares under quadruple = the image of all under square = the image of squares under square = the image of squares under septuple
theorem the_coil_on_zero_one_four_seven_has_5_expressions :
  (([0, 1, 4, 7]).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 4, 7]).contains x))
  && (([0, 1, 4, 7].map (fun d => m9 (4 * d))).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (4 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (4 * d))).eraseDups.length == 4)
  && (([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d))).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d))).contains x) && ([0, 1, 2, 3, 4, 5, 6, 7, 8].map (fun d => m9 (d * d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (d * d))).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (d * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (d * d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (7 * d))).all (fun x => [0, 1, 4, 7].contains x) && [0, 1, 4, 7].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (7 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (7 * d))).eraseDups.length == 4) := by decide

-- 4 expressions, one extension: the image of squares under double = the image of squares under negate = the image of squares under quintuple = the image of squares under octuple
theorem the_coil_on_zero_two_five_eight_has_4_expressions :
  (([0, 1, 4, 7].map (fun d => m9 (2 * d))).all (fun x => [0, 2, 5, 8].contains x) && [0, 2, 5, 8].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (2 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (2 * d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (9 - d))).all (fun x => [0, 2, 5, 8].contains x) && [0, 2, 5, 8].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (9 - d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (9 - d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (5 * d))).all (fun x => [0, 2, 5, 8].contains x) && [0, 2, 5, 8].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (5 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (5 * d))).eraseDups.length == 4)
  && (([0, 1, 4, 7].map (fun d => m9 (8 * d))).all (fun x => [0, 2, 5, 8].contains x) && [0, 2, 5, 8].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (8 * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (8 * d))).eraseDups.length == 4) := by decide

-- 3 expressions, one extension: the set reflfixed = the image of reflfixed under reflect = the fixed points of reflect
theorem the_coil_on_five_has_3_expressions :
  (([5]).all (fun x => [5].contains x) && [5].all (fun x => ([5]).contains x))
  && (([5].map (fun d => m9 (10 - d))).all (fun x => [5].contains x) && [5].all (fun x => ([5].map (fun d => m9 (10 - d))).contains x) && ([5].map (fun d => m9 (10 - d))).eraseDups.length == 1)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (10 - d) == d)).all (fun x => [5].contains x) && [5].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (10 - d) == d)).contains x)) := by decide

-- 3 expressions, one extension: the image of reflfixed under double = the image of selfinv under square = the image of tetA under cube
theorem the_coil_on_one_has_3_expressions :
  (([5].map (fun d => m9 (2 * d))).all (fun x => [1].contains x) && [1].all (fun x => ([5].map (fun d => m9 (2 * d))).contains x) && ([5].map (fun d => m9 (2 * d))).eraseDups.length == 1)
  && (([1, 8].map (fun d => m9 (d * d))).all (fun x => [1].contains x) && [1].all (fun x => ([1, 8].map (fun d => m9 (d * d))).contains x) && ([1, 8].map (fun d => m9 (d * d))).eraseDups.length == 1)
  && (([1, 4, 7].map (fun d => m9 (d * d * d))).all (fun x => [1].contains x) && [1].all (fun x => ([1, 4, 7].map (fun d => m9 (d * d * d))).contains x) && ([1, 4, 7].map (fun d => m9 (d * d * d))).eraseDups.length == 1) := by decide

-- 3 expressions, one extension: the image of tetA under triple = the image of tetB under sextuple = the image of reflfixed under sextuple
theorem the_coil_on_three_has_3_expressions :
  (([1, 4, 7].map (fun d => m9 (3 * d))).all (fun x => [3].contains x) && [3].all (fun x => ([1, 4, 7].map (fun d => m9 (3 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (3 * d))).eraseDups.length == 1)
  && (([2, 5, 8].map (fun d => m9 (6 * d))).all (fun x => [3].contains x) && [3].all (fun x => ([2, 5, 8].map (fun d => m9 (6 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (6 * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (6 * d))).all (fun x => [3].contains x) && [3].all (fun x => ([5].map (fun d => m9 (6 * d))).contains x) && ([5].map (fun d => m9 (6 * d))).eraseDups.length == 1) := by decide

-- 3 expressions, one extension: the image of tetB under triple = the image of reflfixed under triple = the image of tetA under sextuple
theorem the_coil_on_six_has_3_expressions :
  (([2, 5, 8].map (fun d => m9 (3 * d))).all (fun x => [6].contains x) && [6].all (fun x => ([2, 5, 8].map (fun d => m9 (3 * d))).contains x) && ([2, 5, 8].map (fun d => m9 (3 * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (3 * d))).all (fun x => [6].contains x) && [6].all (fun x => ([5].map (fun d => m9 (3 * d))).contains x) && ([5].map (fun d => m9 (3 * d))).eraseDups.length == 1)
  && (([1, 4, 7].map (fun d => m9 (6 * d))).all (fun x => [6].contains x) && [6].all (fun x => ([1, 4, 7].map (fun d => m9 (6 * d))).contains x) && ([1, 4, 7].map (fun d => m9 (6 * d))).eraseDups.length == 1) := by decide

-- 3 expressions, one extension: the image of cubes under square = the image of squares under cube = the fixed points of square
theorem the_coil_on_zero_one_has_3_expressions :
  (([0, 1, 8].map (fun d => m9 (d * d))).all (fun x => [0, 1].contains x) && [0, 1].all (fun x => ([0, 1, 8].map (fun d => m9 (d * d))).contains x) && ([0, 1, 8].map (fun d => m9 (d * d))).eraseDups.length == 2)
  && (([0, 1, 4, 7].map (fun d => m9 (d * d * d))).all (fun x => [0, 1].contains x) && [0, 1].all (fun x => ([0, 1, 4, 7].map (fun d => m9 (d * d * d))).contains x) && ([0, 1, 4, 7].map (fun d => m9 (d * d * d))).eraseDups.length == 2)
  && (([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (d * d) == d)).all (fun x => [0, 1].contains x) && [0, 1].all (fun x => ([0,1,2,3,4,5,6,7,8].filter (fun d => m9 (d * d) == d)).contains x)) := by decide

-- 3 expressions, one extension: the image of tetB under cube = the image of reflfixed under cube = the image of reflfixed under septuple
theorem the_coil_on_eight_has_3_expressions :
  (([2, 5, 8].map (fun d => m9 (d * d * d))).all (fun x => [8].contains x) && [8].all (fun x => ([2, 5, 8].map (fun d => m9 (d * d * d))).contains x) && ([2, 5, 8].map (fun d => m9 (d * d * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (d * d * d))).all (fun x => [8].contains x) && [8].all (fun x => ([5].map (fun d => m9 (d * d * d))).contains x) && ([5].map (fun d => m9 (d * d * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (7 * d))).all (fun x => [8].contains x) && [8].all (fun x => ([5].map (fun d => m9 (7 * d))).contains x) && ([5].map (fun d => m9 (7 * d))).eraseDups.length == 1) := by decide

-- 2 expressions, one extension: the image of cubes under double = the image of cubes under septuple
theorem the_coil_on_zero_two_seven_has_2_expressions :
  (([0, 1, 8].map (fun d => m9 (2 * d))).all (fun x => [0, 2, 7].contains x) && [0, 2, 7].all (fun x => ([0, 1, 8].map (fun d => m9 (2 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (2 * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (7 * d))).all (fun x => [0, 2, 7].contains x) && [0, 2, 7].all (fun x => ([0, 1, 8].map (fun d => m9 (7 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (7 * d))).eraseDups.length == 3) := by decide

-- 2 expressions, one extension: the image of selfinv under double = the image of selfinv under septuple
theorem the_coil_on_two_seven_has_2_expressions :
  (([1, 8].map (fun d => m9 (2 * d))).all (fun x => [2, 7].contains x) && [2, 7].all (fun x => ([1, 8].map (fun d => m9 (2 * d))).contains x) && ([1, 8].map (fun d => m9 (2 * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (7 * d))).all (fun x => [2, 7].contains x) && [2, 7].all (fun x => ([1, 8].map (fun d => m9 (7 * d))).contains x) && ([1, 8].map (fun d => m9 (7 * d))).eraseDups.length == 2) := by decide

-- 2 expressions, one extension: the image of cubes under quadruple = the image of cubes under quintuple
theorem the_coil_on_zero_four_five_has_2_expressions :
  (([0, 1, 8].map (fun d => m9 (4 * d))).all (fun x => [0, 4, 5].contains x) && [0, 4, 5].all (fun x => ([0, 1, 8].map (fun d => m9 (4 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (4 * d))).eraseDups.length == 3)
  && (([0, 1, 8].map (fun d => m9 (5 * d))).all (fun x => [0, 4, 5].contains x) && [0, 4, 5].all (fun x => ([0, 1, 8].map (fun d => m9 (5 * d))).contains x) && ([0, 1, 8].map (fun d => m9 (5 * d))).eraseDups.length == 3) := by decide

-- 2 expressions, one extension: the image of selfinv under quadruple = the image of selfinv under quintuple
theorem the_coil_on_four_five_has_2_expressions :
  (([1, 8].map (fun d => m9 (4 * d))).all (fun x => [4, 5].contains x) && [4, 5].all (fun x => ([1, 8].map (fun d => m9 (4 * d))).contains x) && ([1, 8].map (fun d => m9 (4 * d))).eraseDups.length == 2)
  && (([1, 8].map (fun d => m9 (5 * d))).all (fun x => [4, 5].contains x) && [4, 5].all (fun x => ([1, 8].map (fun d => m9 (5 * d))).contains x) && ([1, 8].map (fun d => m9 (5 * d))).eraseDups.length == 2) := by decide

-- 2 expressions, one extension: the image of reflfixed under negate = the image of reflfixed under octuple
theorem the_coil_on_four_has_2_expressions :
  (([5].map (fun d => m9 (9 - d))).all (fun x => [4].contains x) && [4].all (fun x => ([5].map (fun d => m9 (9 - d))).contains x) && ([5].map (fun d => m9 (9 - d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (8 * d))).all (fun x => [4].contains x) && [4].all (fun x => ([5].map (fun d => m9 (8 * d))).contains x) && ([5].map (fun d => m9 (8 * d))).eraseDups.length == 1) := by decide

-- 2 expressions, one extension: the image of units under reflect = the image of orbit under reflect
theorem the_coil_on_zero_two_three_five_six_eight_has_2_expressions :
  (([1, 2, 4, 5, 7, 8].map (fun d => m9 (10 - d))).all (fun x => [0, 2, 3, 5, 6, 8].contains x) && [0, 2, 3, 5, 6, 8].all (fun x => ([1, 2, 4, 5, 7, 8].map (fun d => m9 (10 - d))).contains x) && ([1, 2, 4, 5, 7, 8].map (fun d => m9 (10 - d))).eraseDups.length == 6)
  && (([1, 2, 4, 8, 7, 5].map (fun d => m9 (10 - d))).all (fun x => [0, 2, 3, 5, 6, 8].contains x) && [0, 2, 3, 5, 6, 8].all (fun x => ([1, 2, 4, 8, 7, 5].map (fun d => m9 (10 - d))).contains x) && ([1, 2, 4, 8, 7, 5].map (fun d => m9 (10 - d))).eraseDups.length == 6) := by decide

-- 2 expressions, one extension: the image of reflfixed under square = the image of reflfixed under quintuple
theorem the_coil_on_seven_has_2_expressions :
  (([5].map (fun d => m9 (d * d))).all (fun x => [7].contains x) && [7].all (fun x => ([5].map (fun d => m9 (d * d))).contains x) && ([5].map (fun d => m9 (d * d))).eraseDups.length == 1)
  && (([5].map (fun d => m9 (5 * d))).all (fun x => [7].contains x) && [7].all (fun x => ([5].map (fun d => m9 (5 * d))).contains x) && ([5].map (fun d => m9 (5 * d))).eraseDups.length == 1) := by decide

end Coils
