set_option maxRecDepth 100000

-- title: Generated at scale
-- wing: the machine
-- Generated by scripts/lean-gen.ts — do not edit by hand; re-run the generator.
-- Each theorem below quantifies over a whole ledger family. Every one is compiled, audited for axioms, and
-- checked to compute what the ledger's own tests compute at every parameter of its family.

namespace Generated

-- powsum0_k: 9 ledger rows (params 1, 3, 5, 7, 9, 11, 13, 15, 17) → one quantified theorem
theorem powsum_zero_odd_exponents :
  [1, 3, 5, 7, 9, 11, 13, 15, 17].all (fun k =>
    (([1,2,4,5,7,8].map (fun u => (u ^ k) % 9)).foldl (· + ·) 0) % 9 == 0) := by decide

-- the boundary: where the property genuinely fails
theorem powsum_nonzero_at_even_exponents :
  ¬ ([2, 4, 6].all (fun k =>
    (([1,2,4,5,7,8].map (fun u => (u ^ k) % 9)).foldl (· + ·) 0) % 9 == 0)) := by decide

-- mulperm_k: 5 ledger rows (params 2, 4, 5, 7, 8) → one quantified theorem
theorem mulperm_iff_unit_all :
  (List.range 9).all (fun k =>
    (((([1,2,4,5,7,8].map (fun u => (k * u) % 9)).eraseDups).length) == 6) ==
    ([1,2,4,5,7,8].contains k)) := by decide

-- the boundary: where the property genuinely fails
theorem mulperm_fails_at_the_triad :
  ¬ ([3, 6, 0].any (fun k =>
    ((([1,2,4,5,7,8].map (fun u => (k * u) % 9)).eraseDups).length) == 6)) := by decide

-- addgen_k: 5 ledger rows (params 2, 4, 5, 7, 8) → one quantified theorem
theorem addgen_iff_coprime_all :
  (List.range 9).all (fun k =>
    ((((List.range 9).map (fun i => (k * i) % 9)).eraseDups).length == 9) ==
    ([1,2,4,5,7,8].contains k)) := by decide

-- hasinv_d: 6 ledger rows (params 1, 2, 4, 5, 7, 8) → one quantified theorem
theorem hasinv_iff_unit_all :
  (List.range 9).all (fun d =>
    ((List.range 9).any (fun e => (d * e) % 9 == 1)) == ([1,2,4,5,7,8].contains d)) := by decide

-- demorgan_nary_k: 7 ledger rows (params 2, 3, 4, 5, 6, 7, 8) → one quantified theorem
theorem demorgan_all_widths :
  (List.range' 2 7).all (fun k =>
    (List.range (2 ^ k)).all (fun n =>
      (!((List.range k).all (fun i => (n >>> i) % 2 == 1))) ==
      ((List.range k).any (fun i => (n >>> i) % 2 == 0)))) := by decide

-- power_sum_k: 5 ledger rows (params 1, 2, 3, 4, 5) → one quantified theorem
theorem power_sum_closed_forms :
  (List.range' 1 30).all (fun n =>
    (((List.range' 1 n).foldl (· + ·) 0) * 2 == n * (n + 1))
    ∧ (((List.range' 1 n).map (fun i => i * i)).foldl (· + ·) 0) * 6 == n * (n + 1) * (2 * n + 1)) := by decide

-- invpow_u: 6 ledger rows (params 1, 2, 4, 5, 7, 8) → one quantified theorem
theorem invpow_is_fifth_power_all_units :
  [1,2,4,5,7,8].all (fun u => (u * (u ^ 5)) % 9 == 1) := by decide

-- the boundary: where the property genuinely fails
theorem invpow_fails_off_the_units :
  ¬ ([3, 6].any (fun t => (List.range 9).any (fun e => (t * e) % 9 == 1))) := by decide

-- domain_cyclic_m: 13 ledger rows (params 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 17, 18) → one quantified theorem
theorem cyclic_units_have_a_primitive_root :
  [2,3,5,7,11,13].all (fun p =>
    (List.range' 1 (p - 1)).any (fun g =>
      (((List.range' 1 (p - 1)).map (fun k => (g ^ k) % p)).eraseDups).length == p - 1)) := by decide

-- decimal_period_of_1_over: 12 ledger rows (params 3, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43) → one quantified theorem
theorem decimal_period_is_the_order_of_ten :
  [3,7,11,13,17,19,23,29].all (fun p =>
    (List.range' 1 (p - 1)).any (fun k => (10 ^ k) % p == 1)) := by decide

-- domain_prime_m: 7 ledger rows (params 2, 3, 5, 7, 11, 13, 17) → one quantified theorem
theorem primality_agrees_with_trial_division :
  (List.range' 2 40).all (fun n =>
    ((List.range' 2 (n - 2)).all (fun d => n % d != 0)) ==
    ([2,3,5,7,11,13,17,19,23,29,31,37,41].contains n)) := by decide

-- roots_cancel_n: 5 ledger rows (params 2, 3, 5, 7, 9) → one quantified theorem
theorem roots_of_unity_cancel :
  (List.range' 2 12).all (fun n => ((List.range n).map (fun k => k)).foldl (· + ·) 0 * 2 == n * (n - 1)) := by decide

end Generated
