set_option maxRecDepth 8000000
-- title: The rays, read forward and reverse, and the mark a life carries
-- wing: the address
-- prior_art: named
-- prior_art_domain: cyclic groups and primitive roots
-- prior_art_note: that 3 is a primitive root modulo 7 and that (ℤ/7)* is cyclic of order six is Gauss and
--   is elementary number theory; the involution x ↦ ¬x on bit words is Boolean algebra. Neither is this
--   deposit's. What is decided here is only that THIS deposit's ray order is that orbit and that its trace
--   is that involution — the facts a reader would otherwise have to take from a comment.
-- Author: Tsvetan Rouschev · License: CC BY-NC-ND 4.0
--
-- A receipt is plotted as RAYS: two hex digits each. Seven of them read 14 of a receipt's 32 hex digits and
-- discarded the other 18, and the extraction was written out twice — once in the page component that draws
-- the figure on every theorem page and once in the script that builds the cluster lattice, with nothing
-- comparing them. One derivation now (src/7/rays.ts), read forward AND reverse: the 2×7 the deposit's own
-- signature lattice already stands on, 28 of 32 digits.
--
-- THE ORDER IS THE GROUP'S, NOT THE BYTE LAYOUT'S. Reading rays 0,1,2,…,6 orders them by where their bytes
-- happen to fall. Seven decomposes as SIX UNITS AND ONE: (ℤ/7)* is cyclic of order six generated by 3, and
-- the seventh element is the class of 0 — the same C6 the doubling orbit traces in ℤ/9, which is this
-- deposit's rosetta. So the rays are visited in that orbit, and the reverse direction walks it backwards.
--
-- No axioms, no Mathlib, no sorry.

namespace Rays

def G : Nat := 3      -- the generator
def N : Nat := 7      -- the dimensions

/-- the orbit of the generator in (ℤ/7)*, derived rather than written down -/
def orbit : Nat → Nat → List Nat
  | 0, _ => []
  | Nat.succ k, x => let y := (x * G) % N; y :: orbit k y

def vortexOrder : List Nat := 0 :: orbit (N - 1) 1
def vortexReversed : List Nat := 0 :: (orbit (N - 1) 1).reverse

-- ── THE ORDER IS A PERMUTATION OF THE SEVEN, and that is the only thing that makes it safe to read by ────
theorem the_orbit_is_the_six_units :
  orbit 6 1 = [3, 2, 6, 4, 5, 1] ∧ (orbit 6 1).length = 6 := by decide

theorem the_order_visits_every_ray_exactly_once :
  vortexOrder.length = 7 ∧ (vortexOrder.eraseDups).length = 7
    ∧ (List.range 7).all (fun i => vortexOrder.contains i) := by decide

theorem the_reversed_order_is_also_a_permutation :
  vortexReversed.length = 7 ∧ (vortexReversed.eraseDups).length = 7
    ∧ (List.range 7).all (fun i => vortexReversed.contains i) := by decide

-- and the two senses are genuinely different, or the 2×7 would be one seven written twice
theorem the_two_senses_are_not_the_same_walk :
  vortexOrder ≠ vortexReversed ∧ vortexOrder.head? = vortexReversed.head? := by decide

-- reversing twice returns the walk: the pair of directions is itself an involution
theorem reversing_the_sense_twice_is_the_identity :
  (0 :: ((vortexReversed.tail).reverse)) = vortexOrder := by decide

-- ── THE MARK: THE INVERTED LOWER-BIT TRACE ───────────────────────────────────────────────────────────────
-- The lattice takes each ray mod 9, and `% 9` over a byte is not injective, so the coordinates throw
-- information away. The low bit of each ray is some of what they throw away — fourteen bits the lattice
-- cannot see. Inverted, because inversion is the involution that makes a trace a mark and not a copy.
def invert (t : List Nat) : List Nat := t.map (fun b => 1 - b)
def lowBits (rs : List Nat) : List Nat := rs.map (fun v => v % 2)

theorem inverting_twice_is_the_identity :
  ((List.range 40).map (fun n => invert (invert (lowBits [n, n + 1, n + 2])) == lowBits [n, n + 1, n + 2])).all id := by decide

-- a trace and its inversion agree nowhere: that is the whole content of the word "inverted"
theorem a_trace_and_its_inversion_agree_nowhere :
  (List.range 40).all (fun n =>
    let t := lowBits [n, n + 1, n + 2, n + 3]
    (List.range 4).all (fun i => (t.getD i 0) + ((invert t).getD i 0) == 1)) := by decide

-- and the trace is not constant: it separates receipts the coordinates alone would place together
theorem the_low_bit_sees_what_the_residue_cannot :
  (0 % 9 == 9 % 9) ∧ (0 % 9 == 18 % 9) ∧ ¬ (0 % 2 == 9 % 2) := by decide

-- ── THE LATTICE'S SHAPE ──────────────────────────────────────────────────────────────────────────────────
def DIMENSIONS : Nat := 2 * N
def DIGITS_READ : Nat := 4 * N
def DIGITS_TOTAL : Nat := 32

theorem the_two_by_seven_reads_more_than_the_seven :
  DIMENSIONS = 14 ∧ DIGITS_READ = 28 ∧ 2 * N = 14 ∧ DIGITS_READ > 2 * N := by decide

theorem four_digits_stay_unread_and_are_counted :
  DIGITS_TOTAL - DIGITS_READ = 4 ∧ DIGITS_READ < DIGITS_TOTAL := by decide

-- ── THE DISTANCE IS A DISTANCE, on the torus where 0 and 8 are one apart and not eight ───────────────────
def d1 (a b : Nat) : Nat := let x := if a < b then b - a else a - b; min x (9 - x)

theorem the_wrap_is_what_makes_it_a_torus :
  d1 0 8 = 1 ∧ d1 8 0 = 1 ∧ d1 0 4 = 4 ∧ d1 4 0 = 4 := by decide

theorem the_distance_is_symmetric_and_zero_only_on_itself :
  (List.range 9).all (fun a => (List.range 9).all (fun b =>
    (d1 a b == d1 b a) && ((d1 a b == 0) == (a == b)))) := by decide

theorem the_triangle_inequality_holds_on_every_triple :
  (List.range 9).all (fun a => (List.range 9).all (fun b => (List.range 9).all (fun c =>
    decide (d1 a c ≤ d1 a b + d1 b c)))) := by decide

def settledHere : Nat := 13
theorem rays_settles_its_range : settledHere = 13 := rfl

end Rays
