-- GENERATED by scripts/settled.ts — do not edit. Regenerate with `npm run settled`.
-- title: What each file says it settles, checked against what it does
-- wing: the record
-- prior_art: unclassified
-- prior_art_domain: elementary arithmetic and list operations on naturals — zip, sum by fold, deduplication,
--   and comparison. None of it is this deposit's and none of it is new.
-- prior_art_note: THE ARITHMETIC IS NAMED, NOT CLAIMED. What is this deposit's is only the subject: that
--   these particular files' self-declared counts agree with their own contents. The statement is about this
--   tree and asserts nothing about anybody else's work.
-- prior_art_search: not performed — the arithmetic is named above rather than searched for, and the subject
--   is this deposit's own sources, where there is nothing to search.
-- prior_art_pool: bounded
-- prior_art_own: the agreement between each file's declared count and its measured contents
-- Author: Tsvetan Rouschev · License: CC BY-NC-ND 4.0
--
-- 15 source files declare `settledHere` — the count of declarations that file closes by exhaustion.
-- Until this file existed each was followed by `theorem …_settles_its_range : settledHere = N := rfl`, a
-- constant compared to itself. seal-lean refused to seal every one of them as "a declaration, not algebra",
-- so the numbers a reader quotes were hand-maintained with nothing checking them and a tautology standing
-- where the check should have been.
--
-- THE TWO COLUMNS COME FROM INDEPENDENT READS OF THE SAME FILES. `declared` names the imported
-- `settledHere` defs directly, so Lean reads each hand-set constant out of its own source; `measured` is
-- written here by the generator from a parse of the `by decide` theorems. Nothing in this file can make them
-- agree — adding a `by decide` theorem to any of them without bumping its count stops this file compiling.
--
-- WHAT THIS DOES NOT SAY: nothing here judges whether a count is the RIGHT measure of what a file settles,
-- and nothing here checks the theorems themselves. It checks that a file's own declaration about itself
-- matches its own contents. No axioms, no Mathlib, no sorry.
import Address
import Asymmetric
import Elementary
import Families
import Fnv
import Imprint
import Instruments
import Merkle
import Program
import Quantum
import Rays
import Reversal
import Rights
import Roots
import Z9

namespace Settled

def files    : List String := ["address.lean", "asymmetric.lean", "elementary.lean", "families.lean", "fnv.lean", "imprint.lean", "instruments.lean", "merkle.lean", "program.lean", "quantum.lean", "rays.lean", "reversal.lean", "rights.lean", "roots.lean", "z9.lean"]
def declared : List Nat := [Address.settledHere, Asymmetric.settledHere, Elementary.settledHere, Families.settledHere, Fnv.settledHere, Imprint.settledHere, Instruments.settledHere, Merkle.settledHere, Program.settledHere, Quantum.settledHere, Rays.settledHere, Reversal.settledHere, Rights.settledHere, Roots.settledHere, Z9.settledHere]

-- measured by scripts/settled.ts from the tree: `by decide` theorems, then all theorems, per file
def measured  : List Nat := [20, 11, 32, 42, 12, 9, 28, 16, 21, 11, 13, 8, 8, 7, 21]
def theorems  : List Nat := [25, 11, 40, 63, 14, 9, 28, 16, 21, 11, 13, 29, 8, 7, 24]
def byRfl     : List Nat := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
def byOther   : List Nat := [5, 0, 8, 21, 2, 0, 0, 0, 0, 0, 0, 21, 0, 0, 3]

-- ── 1 · EVERY FILE SETTLES EXACTLY WHAT IT DECLARES ───────────────────────────────────────────────────────
-- The drift check, row by row. The left side is the constant in the source file; the right side is the count
-- of its exhaustive theorems. This is the theorem the fifteen tautologies were standing in for.
theorem every_file_settles_exactly_what_it_declares :
  (declared.zip measured).all (fun p => p.1 == p.2)
  ∧ declared.length == measured.length
  ∧ declared.length == files.length
  ∧ declared.length == 15 := by decide

-- ── 2 · AND NO FILE DECLARES MORE THAN IT HOLDS ───────────────────────────────────────────────────────────
-- The exhaustive theorems are a SUBSET of the theorems, so the declared count is bounded above by the total
-- and the difference is the declarations closing some other way. A count exceeding the file's own theorems
-- would be impossible rather than merely wrong, and that direction is now decided too.
theorem no_file_declares_more_than_it_holds :
  (declared.zip theorems).all (fun p => p.1 ≤ p.2)
  ∧ (measured.zip theorems).all (fun p => p.1 ≤ p.2) := by decide

-- ── 3 · THE PARTS SUM TO THE WHOLE, AND EACH PART IS RECOVERABLE ──────────────────────────────────────────
-- Conservation with its inverse: the declared counts add to the same total the measured ones do, and removing
-- any one file's count leaves exactly the rest — so no row can be quietly absorbed into another.
theorem the_parts_sum_to_the_whole_and_each_part_is_recoverable :
  declared.foldl (· + ·) 0 == measured.foldl (· + ·) 0
  ∧ declared.foldl (· + ·) 0 == 259
  ∧ (List.range declared.length).all (fun i =>
      declared.foldl (· + ·) 0 - declared.getD i 0
        == ((List.range declared.length).filter (fun j => j != i)).foldl
             (fun a j => a + declared.getD j 0) 0) := by decide

-- ── 4 · NO FILE SETTLES NOTHING ───────────────────────────────────────────────────────────────────────────
-- A file declaring zero would pass row 1 by holding no exhaustive theorem at all, which is agreement without
-- content. Every count is positive, so every row above is a claim about something.
theorem no_file_settles_nothing :
  declared.all (fun n => 0 < n) ∧ measured.all (fun n => 0 < n) := by decide

-- ── 5 · THE CONTROL: THE AGREEMENT IS NOT ONE NUMBER REPEATED ─────────────────────────────────────────────
-- THE THEOREM THAT STOPS ROW 1 FROM BEING VACUOUS. Row-wise equality between two lists would hold trivially
-- if every entry were the same value, so it is decided here that the counts genuinely differ: the distinct
-- values number more than one, and the extremes are far apart. Without this, a generator that emitted a
-- constant column would read as green.
theorem the_counts_are_not_one_number_repeated :
  1 < declared.eraseDups.length
  ∧ declared.eraseDups.length == 12
  ∧ (declared.foldl (fun a b => if a < b then b else a) 0)
      > (declared.foldl (fun a b => if b < a then b else a) 1000) := by decide

-- ── 6 · AND EACH FILE IS COUNTED ONCE ─────────────────────────────────────────────────────────────────────
-- Two rows for one file would double it in the total while every row still agreed with itself. The names are
-- distinct, so the sum above is over fifteen files and not fourteen files and a repeat.
theorem each_file_is_counted_once :
  files.eraseDups.length == files.length
  ∧ files.length == 15 := by decide

-- ── 7 · THE TWO PROOF STYLES PARTITION THE THEOREMS, AND NEITHER IS A DECLARATION ─────────────────────────
-- What is not closed by exhaustion is closed by a tactic block over a ∀ — a THEOREM, proved for every value.
-- The two counts add to the file's total and neither overlaps the other, so "not by decide" and "a declaration"
-- are different things and the difference is decided here rather than assumed.
theorem the_two_proof_styles_partition_the_theorems :
  ((measured.zip byOther).map (fun p => p.1 + p.2)) == theorems
  ∧ measured.foldl (· + ·) 0 + byOther.foldl (· + ·) 0 == theorems.foldl (· + ·) 0
  ∧ (measured.zip theorems).all (fun p => p.1 ≤ p.2) := by decide

-- ── 8 · AND NOT ONE DECLARATION IN THESE FILES CLOSES BY rfl ───────────────────────────────────────────────
-- THE THEOREM THAT FALSIFIES A SENTENCE THIS DEPOSIT WAS PUBLISHING. scripts/pages.ts wrote, on the README
-- and the index, "the remaining N close by rfl and are declarations", computing N as the total less the
-- by-decide count — which treats every proof that is not an exhaustion as an rfl declaration. They are not:
-- they are ∀-quantified theorems. Among the 15 that declare a count the rfl total is zero, so the
-- sentence named a population that does not exist — every genuine rfl declaration that used to live in them
-- was a `settledHere = N` tautology, and each one is gone. What that
-- subtraction actually counts is byOther, and THAT is the conjunct below: the quantity pages.ts labelled rfl
-- equals the ∀-proved theorems at every row, so the label was wrong about every one of them.
theorem no_declaration_in_these_files_closes_by_rfl :
  byRfl.all (fun n => n == 0)
  ∧ byRfl.foldl (· + ·) 0 == 0
  ∧ ((theorems.zip measured).map (fun p => p.1 - p.2)) == byOther := by decide

end Settled
