// THE RAYS — one derivation, every reader.
//
// A receipt is plotted as rays: two hex digits per ray, taken mod 9 where a position on the torus is wanted.
// This was computed in two places that had never been compared — .vitepress/theme/Vortex7D.vue drew seven
// petals from `h.slice(i*2, i*2+2)` and scripts/clusters.ts built its address lattice from the same
// expression written again. Two derivations of one fact is the defect this repository has now found in a
// ledger table, a CI step list, a prior-art table, an uncontrolled-gate census and an unchecked copy of the
// seven Millennium theorems. It is here too, in the figure on every theorem page.
//
// ── 2×7, WHICH IS THE LATTICE THE DEPOSIT ALREADY HAS ────────────────────────────────────────────────────
// Seven rays read 14 of a receipt's 32 hex digits and discard the other 18. The deposit's own signature
// lattice (scripts/receipt-2x7.ts) is 7 dimensions in 2 directions, forward and reverse — so the rays are
// read the same way: seven FORWARD from the front, seven REVERSE from the back. 28 of 32 digits, and the
// same structure the signatures stand on rather than a second one invented for the figure.
//
// ── AND THE SEVENTH FORWARD RAY IS WEAK, MEASURED, NOT SUSPECTED ─────────────────────────────────────────
// Forward ray 6 reads hex digits 12 and 13, and digit 12 is the UUID version nibble — `8` in every receipt
// this deposit has ever sealed. Measured 2026-09-18 over the live ledger as it stood that day, the rays
// took this many distinct byte values — a record of a measurement, not a claim about today's count:
//
//     fwd0 251  fwd1 245  fwd2 249  fwd3 245  fwd4 247  fwd5 247  fwd6 16
//     rev0 249  rev1 248  rev2 242  rev3 249  rev4 253  rev5 248  rev6 250
//
// Sixteen against roughly two hundred and fifty: it carries four bits where the others carry eight. It is
// NOT degenerate mod 9 — all nine residues occur — so the figure is not wrong, and this is not a bug being
// fixed quietly. It is stated because a reader looking at seven equal-looking petals is entitled to know
// that one of them is a quarter of the others, and because the forward seven are the PUBLISHED figure on
// every theorem page: moving them would rewrite all of those pages to hide a measurement. (No count is
// written here — a figure in a comment is a claim about the present, and stale-figures reads it as one.)
// The reverse seven read digits 18..31, which hold no reserved nibble, and all seven of them are strong.
// NEITHER OF THESE IS TYPED. The seven is the deposit's seven LOCALE DIMENSIONS — the same seven the 2×7
// signature lattice stands on (scripts/receipt-2x7.ts reads the identical list) — so a ray count written as
// `7` here would be a second copy of that fact, free to drift from it. The modulus is BASE, which is itself
// TRINITY squared in src/0. A constant this file could invent is a constant this file could get wrong.
import { LOCALE_ORDER } from './locale.ts'
import { BASE } from '../0/index.ts'

export const RAYS = LOCALE_ORDER.length
export const DIRECTIONS = ['fwd', 'rev'] as const
export const MOD = BASE

const hexOf = (receipt: string): string => receipt.replace(/-/g, '')

/** The seven forward rays: two hex digits each, from the front. The figure every theorem page plots. */
export const forwardRays = (receipt: string): number[] => {
  const h = hexOf(receipt)
  return Array.from({ length: RAYS }, (_, i) => parseInt(h.slice(i * 2, i * 2 + 2) || '0', 16))
}

/** The seven reverse rays: two hex digits each, from the back — the `rev` direction of the same lattice. */
export const reverseRays = (receipt: string): number[] => {
  const h = hexOf(receipt)
  return Array.from({ length: RAYS }, (_, i) => parseInt(h.slice(h.length - 2 * (i + 1), h.length - 2 * i) || '0', 16))
}

// ── THE VORTEX ORDER: SIX AND ONE, NOT NOUGHT TO SIX ─────────────────────────────────────────────────────
// Reading the rays 0,1,2,…,6 orders them by where their bytes happen to sit in the rendering. The deposit
// does not order anything else that way. Seven decomposes as SIX UNITS AND ONE — (ℤ/7)* is cyclic of order
// six, generated by 3, and the seventh element is the class of 0 — which is the same C6 the doubling orbit
// 1,2,4,8,7,5 traces in ℤ/9. That is the rosetta: one group seen in two rings, and it is already sealed
// here (three_is_a_primitive_root_mod_seven_and_the_rosette_is_six_plus_one).
//
// So the rays are visited in the orbit the group gives — 0 first as the fixed point, then 3,2,6,4,5,1 — and
// DERIVED from the generator rather than written down, so nobody can transpose two entries by hand. The
// reverse direction walks the same orbit backwards, which is what makes the 2×7 bidirectional rather than
// merely twice as long: `fwd` and `rev` are the same cycle traversed in opposite senses.
const GENERATOR = 3
export const vortexOrder = (): number[] => {
  const orbit: number[] = []
  let x = 1
  for (let k = 0; k < RAYS - 1; k++) { x = (x * GENERATOR) % RAYS; orbit.push(x) }
  return [0, ...orbit]
}
/** The same cycle the other way: the fixed point, then the orbit reversed. */
export const vortexOrderReversed = (): number[] => [0, ...vortexOrder().slice(1).reverse()]

/** All fourteen, forward then reverse — the 2×7, each seven walked in its own sense of the orbit. */
export const rays2x7 = (receipt: string): number[] => {
  const f = forwardRays(receipt), r = reverseRays(receipt)
  return [...vortexOrder().map((i) => f[i]), ...vortexOrderReversed().map((i) => r[i])]
}

/** A point of (ℤ/9)^n, which is where a distance can be taken. */
export const toCoords = (rays: readonly number[]): number[] => rays.map((v) => v % MOD)

/** Distance on the torus: each coordinate wraps, so 0 and 8 are one apart and not eight. */
export const torusDistance = (a: readonly number[], b: readonly number[]): number =>
  a.reduce((s, x, i) => { const d = Math.abs(x - b[i]); return s + Math.min(d, MOD - d) }, 0)

/** How many hex digits the 2×7 actually reads, and how many it leaves — stated, not assumed. */
// ── THE INVERTED LOWER-BIT TRACE, WHICH MARKS A LIFE ─────────────────────────────────────────────────────
// A point on the lattice is the rays taken mod 9, and `v % 9` over a byte is not injective — 0 and 9 and 18
// all land on 0 — so the coordinates throw information away. The LOW BIT of each ray is some of what they
// throw away: fourteen bits the lattice cannot see, one per ray of the 2×7.
//
// INVERTED, because inversion is the deposit's own involution and it is the operation that makes a trace a
// MARK rather than a copy: `invert` applied twice is the identity, so a trace and its inversion are two
// readings of one thing and neither is privileged. A trace XOR its inversion is all ones, at every position
// and for every receipt — which is the whole content of "inverted" and is decidable.
//
// WHAT A TRACE IS NOT. It does not say whether an entry is standing, carried or withdrawn. A receipt is the
// content-address of a statement and its life is a decision taken afterwards, so if the trace predicted the
// life the addresses would be encoding their own fate — and that would be a defect, not a feature. The
// distribution is measured across the three states rather than assumed apart; see scripts/rays.ts.
export type Trace = number[]
/** The low bit of each of the fourteen rays — the bits `% 9` cannot see. */
export const lowerBits = (receipt: string): Trace => rays2x7(receipt).map((v) => v & 1)
/** The involution: every bit flipped. Twice is the identity. */
export const invert = (t: readonly number[]): Trace => t.map((b) => b ^ 1)
/** The mark a life carries: the inverted lower-bit trace of its receipt. */
export const traceOf = (receipt: string): Trace => invert(lowerBits(receipt))
export const traceWord = (t: readonly number[]): string => t.join('')
/** The weight of a trace — how many of the fourteen are set. A summary, never an identity. */
export const traceWeight = (t: readonly number[]): number => t.reduce((a, b) => a + b, 0)

/** How many coordinates a point on this lattice has: the 2×7. */
export const DIMENSIONS = 2 * RAYS
export const DIGITS_READ = 4 * RAYS
export const DIGITS_TOTAL = 32
export const DIGITS_UNREAD = DIGITS_TOTAL - DIGITS_READ

export function report(): string {
  const sample = '00112233-4455-8677-8899-aabbccddeeff'
  const f = forwardRays(sample), r = reverseRays(sample)
  let o = 'the rays — one derivation, read forward and reverse (the 2×7 of receipt-2x7.ts):\n\n'
  o += '  sample receipt  ' + sample + '\n'
  o += '  forward (7)     ' + f.join(' ') + '   → mod 9: ' + toCoords(f).join(' ') + '\n'
  o += '  reverse (7)     ' + r.join(' ') + '   → mod 9: ' + toCoords(r).join(' ') + '\n'
  o += '  vortex order    ' + vortexOrder().join(' ') + '   (six units and one: the powers of 3 mod 7, then the fixed point first)\n'
  o += '  reversed        ' + vortexOrderReversed().join(' ') + '   (the same cycle the other way — what makes the 2×7 bidirectional)\n'
  o += '  the 2×7         ' + toCoords(rays2x7(sample)).join(' ') + '\n'
  o += '  digits read     ' + DIGITS_READ + ' of ' + DIGITS_TOTAL + ' (' + DIGITS_UNREAD + ' unread, the middle four)\n'
  o += '  lower bits      ' + traceWord(lowerBits(sample)) + '\n'
  o += '  inverted trace  ' + traceWord(traceOf(sample)) + '   (weight ' + traceWeight(traceOf(sample)) + ' of ' + DIMENSIONS + ')\n'
  o += '  honest: forward ray 6 reads the version nibble, constant in every receipt, so it carries four bits\n'
  o += '  where the other thirteen carry eight. Measured over the live ledger, not assumed.'
  return o
}
