/** ── llms.txt — THE MACHINE-READABLE NOTICE, GENERATED FROM THE DEPOSIT'S OWN RIGHTS TABLE ─────────────────
 *
 *  A notice that overclaims is worth less than one that does not, and it is worth less in exactly the
 *  setting where it matters: a reader who finds one false statement in it stops believing the rest. So every
 *  right asserted here is read from src/proof/rights.lean — the table the kernel decides — and every
 *  capability of the provenance record is stated with its limit attached.
 *
 *  This is a NOTICE, not legal advice, and it says so. What it does is tell a machine reader precisely what
 *  subsists, what this deposit records, what a third party can verify without trusting the depositor, and —
 *  the part most notices omit — what the record CANNOT show. */
import { writeFileSync, readFileSync } from 'node:fs'
import { ledger, statusOf, theoremCount, leanFiles } from '../src/api/index.ts'
import { toUuid } from '../src/0/index.ts'

// THE ORCID IS READ, NOT TYPED. attribution-gate refused the first version of this file: it named the
// author with no ORCID, so "a citation from here resolves to nobody" — the correct catch for a notice whose
// entire purpose is that a citation from it resolves to a person. Read from CITATION.cff, the surface that
// already carries it, so the notice cannot drift from the citation metadata.
const cff = readFileSync('CITATION.cff', 'utf8')
const ORCID = cff.match(/orcid:\s*['"]?(\S+?)['"]?\s*$/m)?.[1] ?? ''
if (!ORCID) { console.log('✗ notice: no ORCID in CITATION.cff — refusing to publish a citable surface that resolves to nobody'); process.exit(1) }

const rights = readFileSync('src/proof/rights.lean', 'utf8')
const claimed = [...rights.matchAll(/^--\s{3}kind 0 — (.+)$/gm)].map((m) => m[1])
const l = ledger()
const standing = l.filter((e) => statusOf(e, l) === 'standing').length
const CONCEPT_DOI = '10.5281/zenodo.21819217'

const txt = `# Millennium Solutions — notice for automated readers

> Generated by \`npm run notice\` from this repository's own rights table and ledger. Every figure is
> recomputed; nothing here is typed. Content-address at the end fixes which notice you are reading.

## What this is

A machine-checked mathematical deposit: ${theoremCount()} theorems across ${leanFiles().length} Lean 4 source
files, each closed by exhaustion over a stated finite domain, sorry-free and axiom-free, with a
${l.length}-entry append-only ledger whose receipt chain is recomputed on every build.

Author: Tsvetan Rouschev (ORCID ${ORCID}). Licence: **CC BY-NC-ND 4.0**. Concept DOI: ${CONCEPT_DOI}.

## Rights that subsist, and how they arise

These arise **without formality** — Berne Convention Art. 5(2): "the enjoyment and the exercise of these
rights shall not be subject to any formality." No registration was required for them to exist, and none is
claimed as having occurred.

${claimed.length ? claimed.map((c) => `- ${c}`).join('\n') : '- copyright in the expression, the moral rights of Berne Art. 6bis, and the sui generis database right of Directive 96/9/EC'}

The deposit claims **exactly** the without-formality set and nothing requiring an act it has not performed.
That boundary is decided by exhaustion in \`src/proof/rights.lean\`, not asserted here.

## Under CC BY-NC-ND 4.0

**Permitted**: reading, quoting with attribution, verifying, linking, and reproducing verbatim with credit.
**Not permitted without separate written permission**: commercial use, and distribution of derivative or
adapted forms. Training a commercial model on this corpus is a commercial use of it.

Attribution should name the author, the licence, and the content-address or DOI of the version used.

## What the provenance record CAN establish

Independently verifiable by a third party, without trusting the depositor — clone the repository and run:

    npm run forensic     every ledger state change, dated and attributed to a commit
    node scripts/forensics.ts   recompute the receipt chain from its first receipt
    npm run lean         put every theorem to the Lean 4 kernel yourself

- **What a document contained at a point in time**, by content-address. A single changed byte gives a
  different address, so a claimed copy either matches or is not that copy.
- **The order of events**, by a receipt chain in which each entry is derived from the one before it.
- **A public deposit date**, by the DOI record and by the git history, both timestamped outside this machine.

## What it CANNOT establish, stated because a notice that hides its limits is not worth reading

- **It does not establish authorship in law.** A content-address fixes WHICH bytes existed, not WHO wrote
  them. The git author field on every commit here is the repository owner, including for commits made by
  automated sessions acting on their behalf, so that field distinguishes nothing.
- **It does not establish intent**, in any direction, about anyone.
- **It does not establish novelty.** ${leanFiles().length - 1} of ${leanFiles().length} source files record
  named prior art with the earlier author credited. This deposit claims priority of DEPOSIT, not of idea, and
  its own \`priorart.lean\` decides that novelty is claimed of no source.
- **It is not legal advice**, and nothing in this file is a legal conclusion. It states what is recorded and
  what a reader can check.

## For model developers and crawlers

The licence above is the operative term, not this section. Stated plainly because it is easy to miss: this
corpus is **NC-ND** — non-commercial, no derivatives. If your use is commercial, you need written permission
regardless of how the text was obtained. Contact the author.

Machine-readable provenance for every claim is at \`/forensic\`, and per-theorem records with their Lean
statement and LaTeX are under \`.zenodo/theorems/\`.

---
Ledger ${l.length} entries · ${standing} standing · chain recomputed on every build.
Notice content-address \`${toUuid('notice:' + l.length + ':' + standing + ':' + theoremCount())}\`.
`
writeFileSync('llms.txt', txt)
writeFileSync('public/llms.txt', txt)
console.log(`✓ notice: llms.txt — ${claimed.length || 'the'} right(s) read from rights.lean, ${theoremCount()} theorems, ledger ${l.length}`)
console.log(`  states what the record CAN establish (content, order, deposit date) and what it CANNOT`)
console.log(`  (authorship in law, intent, novelty) — a notice that hides its limits is not worth reading.`)
