#!/usr/bin/env node
// ONE-AUTHOR GATE — an artefact generated by two scripts has no author.
//
// README.md was written by BOTH pages.ts and readme.ts, with different prose, and whichever ran last won. So
// the deposit's front page said different things about what it does not claim depending on the order of two
// commands, and the trial that checks that page had been failing for exactly that reason. I nearly "fixed"
// it by changing the sentence the trial looks for.
//
// This finds the general case. It resolves paths written literally AND through a simple `const X = '...'`,
// because half the writes in this repo go through a constant and a check that only sees string literals
// would have missed the ledger's four writers entirely — the same blindness as grepping for the hardcoded
// sets I already remembered.
//
// TWO KINDS OF MULTI-WRITER, and only one is a fault:
//   GENERATOR  — the script writes the whole file from scratch. Two of those is a conflict, always.
//   MUTATOR    — the script reads the file, changes part of it, writes it back. Several of those is how an
//                append-only ledger is meant to work, and sealing, folding and retiring all do it.
// The difference is whether the writer READS the same path first, which is what is measured here rather
// than assumed from the name.
import { readFileSync, readdirSync } from 'node:fs'

const FILES = [
  ...readdirSync('scripts').filter((f) => f.endsWith('.ts')).map((f) => 'scripts/' + f),
  ...readdirSync('src/prove').filter((f) => f.endsWith('.ts')).map((f) => 'src/prove/' + f),
]

type Write = { script: string; path: string; mutates: boolean }
const writes: Write[] = []

for (const f of FILES) {
  const src = readFileSync(f, 'utf8')
  // `const NAME = 'path'` — so a write through a constant resolves to what it actually writes
  const consts = new Map<string, string>()
  for (const m of src.matchAll(/^\s*const\s+([A-Z_][A-Z_0-9]*)\s*(?::\s*string\s*)?=\s*'([^']+)'/gm)) consts.set(m[1], m[2])

  const seen = new Set<string>()
  for (const m of src.matchAll(/writeFileSync\(\s*(?:'([^']+)'|([A-Za-z_][A-Za-z_0-9]*))\s*,/g)) {
    const path = m[1] ?? consts.get(m[2] ?? '') ?? null
    if (!path || path.startsWith('/tmp')) continue        // probes and scratch files are nobody's artefact
    if (seen.has(path)) continue
    seen.add(path)
    // DOES IT READ THE SAME PATH FIRST? Then it is amending, not generating. Reading is no longer only
    // readFileSync: the API migration means the ledger is loaded through `ledger()` from src/api, so a check
    // that looked for the raw call reported four amenders as generators. The indirection this gate had to
    // learn about is one I introduced two commits ago — a checker has to be told when the thing it checks
    // changes shape, and it will not notice on its own.
    const escaped = path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const readsFile = new RegExp(`readFileSync\\(\\s*(?:'${escaped}'|${m[2] ?? '\\u0000'})`).test(src)
    const readsViaApi = path === 'src/proof/discovered.json'
      && /from '\.\.\/src\/api\/index\.ts'/.test(src)
      && /\b(__ledger|ledger|loadLedger|ledgerOf)\s*\(/.test(src)
    const reads = readsFile || readsViaApi
    writes.push({ script: f, path, mutates: reads })
  }
}

const byPath = new Map<string, Write[]>()
for (const w of writes) (byPath.get(w.path) ?? byPath.set(w.path, []).get(w.path)!).push(w)

let bad = 0
const shared = [...byPath.entries()].filter(([, ws]) => ws.length > 1)
console.log(`one-author — ${writes.length} write(s) across ${FILES.length} scripts, ${byPath.size} artefact(s):`)
for (const [path, ws] of shared.sort((a, b) => b[1].length - a[1].length)) {
  const generators = ws.filter((w) => !w.mutates)
  const ok = generators.length <= 1
  if (!ok) bad++
  console.log(`  ${ok ? '·' : '✗'} ${path} — ${ws.length} writers: ${ws.map((w) => w.script.replace('scripts/', '') + (w.mutates ? ' (amends)' : ' (generates)')).join(', ')}`)
  if (!ok) console.log(`      ${generators.length} of them write the whole file, so the last one to run decides what it says`)
}
console.log(bad
  ? `\n✗ one-author: ${bad} artefact(s) have more than one generator — the winner depends on command order`
  : `\n✓ one-author: every generated artefact has a single generator (${shared.length} path(s) with several writers, each amending a file it reads first)`)
process.exit(bad ? 1 : 0)
