#!/usr/bin/env node
// ONE-AUTHOR GATE — an artefact generated by two scripts has no author.
//
// README.md was written by BOTH pages.ts and readme.ts, with different prose, and whichever ran last won. So
// the deposit's front page said different things about what it does not claim depending on the order of two
// commands, and the trial that checks that page had been failing for exactly that reason. I nearly "fixed"
// it by changing the sentence the trial looks for.
//
// This finds the general case. It resolves paths written literally AND through a simple `const X = '...'`,
// because half the writes in this repo go through a constant and a check that only sees string literals
// would have missed the ledger's four writers entirely — the same blindness as grepping for the hardcoded
// sets I already remembered.
//
// TWO KINDS OF MULTI-WRITER, and only one is a fault:
//   GENERATOR  — the script writes the whole file from scratch. Two of those is a conflict, always.
//   MUTATOR    — the script reads the file, changes part of it, writes it back. Several of those is how an
//                append-only ledger is meant to work, and sealing, folding and retiring all do it.
// The difference is whether the writer READS the same path first, which is what is measured here rather
// than assumed from the name.
import { readFileSync, readdirSync } from 'node:fs'

const FILES = [
// gates-fire.ts is excluded BY NECESSITY, not by convenience: it is the file of negative controls, so
// it must contain the very things this gate rejects. Scanning it made this gate fail on a clean tree —
// which gates-fire caught, on its first run, about the gate it was written to test.
  ...readdirSync('scripts').filter((f) => f.endsWith('.ts') && f !== 'gates-fire.ts').map((f) => 'scripts/' + f),
  ...readdirSync('src/prove').filter((f) => f.endsWith('.ts')).map((f) => 'src/prove/' + f),
]

type Write = { script: string; path: string; mutates: boolean }
const writes: Write[] = []

for (const f of FILES) {
  const src = readFileSync(f, 'utf8')
  // `const NAME = 'path'` — so a write through a constant resolves to what it actually writes
  const consts = new Map<string, string>()
  for (const m of src.matchAll(/^\s*const\s+([A-Z_][A-Z_0-9]*)\s*(?::\s*string\s*)?=\s*'([^']+)'/gm)) consts.set(m[1], m[2])

  const seen = new Set<string>()
  for (const m of src.matchAll(/writeFileSync\(\s*(?:'([^']+)'|([A-Za-z_][A-Za-z_0-9]*))\s*,/g)) {
    const path = m[1] ?? consts.get(m[2] ?? '') ?? null
    if (!path || path.startsWith('/tmp')) continue        // probes and scratch files are nobody's artefact
    if (seen.has(path)) continue
    seen.add(path)
    // DOES IT READ THE SAME PATH FIRST? Then it is amending, not generating. Reading is no longer only
    // readFileSync: the API migration means the ledger is loaded through `ledger()` from src/api, so a check
    // that looked for the raw call reported four amenders as generators. The indirection this gate had to
    // learn about is one I introduced two commits ago — a checker has to be told when the thing it checks
    // changes shape, and it will not notice on its own.
    const escaped = path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const readsFile = new RegExp(`readFileSync\\(\\s*(?:'${escaped}'|${m[2] ?? '\\u0000'})`).test(src)
    const readsViaApi = path === 'src/proof/discovered.json'
      && /from '\.\.\/src\/api\/index\.ts'/.test(src)
      && /\b(__ledger|ledger|loadLedger|ledgerOf)\s*\(/.test(src)
    const reads = readsFile || readsViaApi
    writes.push({ script: f, path, mutates: reads })
  }
}

const byPath = new Map<string, Write[]>()
for (const w of writes) (byPath.get(w.path) ?? byPath.set(w.path, []).get(w.path)!).push(w)

let bad = 0
const shared = [...byPath.entries()].filter(([, ws]) => ws.length > 1)
console.log(`one-author — ${writes.length} write(s) across ${FILES.length} scripts, ${byPath.size} artefact(s):`)
for (const [path, ws] of shared.sort((a, b) => b[1].length - a[1].length)) {
  const generators = ws.filter((w) => !w.mutates)
  const ok = generators.length <= 1
  if (!ok) bad++
  console.log(`  ${ok ? '·' : '✗'} ${path} — ${ws.length} writers: ${ws.map((w) => w.script.replace('scripts/', '') + (w.mutates ? ' (amends)' : ' (generates)')).join(', ')}`)
  if (!ok) console.log(`      ${generators.length} of them write the whole file, so the last one to run decides what it says`)
}
// ── A SCRIPT THAT ENUMERATES A DIRECTORY MUST NOT SILENTLY READ ITS OWN OUTPUT ──────────────────────────
// zeropoint-node-8a audited this tree and named the shape from their own day: a record written into a
// directory the same script fingerprints or scans. Theirs was lean/bounds.json living inside the lean/
// directory being fingerprinted — so the write changed the input, the fast path could never be taken, and
// it recomputed every run while appearing to work.
//
// Measured here: three candidate sites and all three already handle it. lean.ts keys its cache on each
// .lean file's OWN bytes, so writing .lean-cache.json beside them changes nothing. sw-integrity.ts SKIPs
// sw.js and sw-integrity.json when building its manifest of dist. imagine.ts reads src/proof/*.lean with
// `f !== 'imagined.lean'`, excluding the file it is about to write.
//
// None of that was held by anything, which is the only reason this exists. A new script enumerating a
// directory it writes into must say why that is safe, here, rather than be correct by the care of whoever
// happened to write it.
const SELF_WRITERS: Record<string, string> = {
  'imagine.ts': 'reads src/proof/*.lean with `f !== imagined.lean`, excluding the file it writes',
  'sw-integrity.ts': 'SKIP holds sw.js and sw-integrity.json, so the manifest never covers itself',
  'lean.ts': 'the cache keys on each .lean file\'s own bytes, not on a listing of the directory',
}
{
  const dirOf = (x: string) => x.replace(/\/[^/]*$/, '') || '.'
  for (const f of readdirSync('scripts').filter((x) => x.endsWith('.ts'))) {
    const src = readFileSync(`scripts/${f}`, 'utf8')
    const reads = new Set<string>(), writes = new Set<string>()
    for (const m of src.matchAll(/readdirSync\(\s*['`]([^'`]+)/g)) reads.add(m[1].replace(/\/+$/, ''))
    for (const m of src.matchAll(/writeFileSync\(\s*['`]([^'`$]+)/g)) writes.add(dirOf(m[1]))
    for (const w of writes) for (const r of reads) {
      if (w !== r && !w.startsWith(r + '/')) continue
      if (SELF_WRITERS[f]) continue
      console.error(`  ✗ ${f} enumerates ${r} and writes into it, with no recorded reason that is safe —`)
      console.error(`    a script that reads its own output either recomputes forever or reads a stale self.`)
      process.exitCode = 1
    }
  }
  console.log(`  ✓ ${Object.keys(SELF_WRITERS).length} script(s) write into a directory they read, each with the exclusion that makes it safe recorded`)
}

console.log(bad
  ? `\n✗ one-author: ${bad} artefact(s) have more than one generator — the winner depends on command order`
  : `\n✓ one-author: every generated artefact has a single generator (${shared.length} path(s) with several writers, each amending a file it reads first)`)
process.exit(bad ? 1 : 0)
