// WHAT EACH FILE SAYS IT SETTLES, CHECKED AGAINST WHAT IT DOES.
//
// Fifteen source files carry `def settledHere : Nat := N` — the count of declarations that file closes by
// exhaustion. Each one used to be followed by `theorem <file>_settles_its_range : settledHere = N := rfl`,
// which compared a constant to itself: it checked the typing and decided nothing, and seal-lean already
// refused to seal any of them ("rfl — a declaration, not algebra"). So fifteen numbers that a reader quotes
// were maintained by hand with NOTHING checking them, and the tautology beside each one looked like a check.
//
// z9.lean records what that costs: its count "read 21 until the count was recomputed against the tree — it
// had been counting itself". A derived number kept by hand drifts, and the drift ships.
//
// THIS GENERATOR CLOSES IT. It parses each file twice, independently:
//
//   · DECLARED — the literal in `def settledHere : Nat := N`. Except it does not emit that literal. The
//     generated file IMPORTS the module and names `Address.settledHere` directly, so Lean reads the hand-set
//     constant out of the source file itself. The generator cannot launder a wrong number into agreement.
//   · MEASURED — the count of `theorem … := by decide` declarations, from the theorem parse.
//
// Only the measured column is written here. That is what makes the equality a check rather than a restatement:
// add a `by decide` theorem to fnv.lean without bumping its count and this file stops compiling.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'

const DIR = 'src/proof'
const OUT = `${DIR}/settled.lean`

type Row = { file: string; mod: string; ns: string; declared: number; byDecide: number; theorems: number
             byRfl: number; byOther: number }

// the files are DERIVED, not listed: whichever files declare a count are the ones checked, so a new one is
// picked up without anybody remembering to add it here, and a removed one stops being asserted about.
const rows: Row[] = []
for (const f of readdirSync(DIR).filter((x) => x.endsWith('.lean')).sort()) {
  const src = readFileSync(`${DIR}/${f}`, 'utf8')
  const decl = src.match(/^\s*def\s+settledHere\s*:\s*Nat\s*:=\s*(\d+)/m)
  if (!decl) continue
  const ns = src.match(/^namespace\s+([A-Za-z_0-9.]+)/m)
  if (!ns) { console.log(`  ✗ ${f} declares settledHere but has no namespace — skipped`); continue }
  // comments stripped first: a `:= by decide` inside prose is not a proof, and counting it read two files one high
  const bare = src.replace(/\/-[\s\S]*?-\//g, '').replace(/--[^\n]*/g, '')
  const ths = [...bare.matchAll(/^\s*theorem\s+([A-Za-z_0-9]+)\s*:([\s\S]*?):=\s*(by\s+\S+|rfl)/gm)]
  rows.push({
    file: f, mod: ns[1], ns: ns[1], declared: Number(decl[1]),
    byDecide: ths.filter((m) => m[3].startsWith('by decide')).length,
    byRfl: ths.filter((m) => m[3] === 'rfl').length,
    // everything that is neither: a ∀-quantified proof closed by a tactic block. These are THEOREMS and
    // they are not declarations, which is the distinction scripts/pages.ts was collapsing.
    byOther: ths.filter((m) => !m[3].startsWith('by decide') && m[3] !== 'rfl').length,
    theorems: ths.length,
  })
}

const drift = rows.filter((r) => r.declared !== r.byDecide)
const total = rows.reduce((a, r) => a + r.declared, 0)
const L = (xs: (string | number)[]) => `[${xs.join(', ')}]`

// REPORTED BEFORE ANYTHING IS WRITTEN. A drifted tree must not get a generated file emitted for it: the file
// would fail in the kernel, and the kernel's message names settled.lean rather than the source file whose
// count is wrong — blaming the instrument's output for the subject's defect, which this deposit has recorded
// before. The exact file and both numbers are named here instead.
if (drift.length) {
  console.log(`✗ settled: ${drift.length} file(s) declare a count the tree does not hold:`)
  for (const r of drift) console.log(`    ${r.file}: declares ${r.declared}, holds ${r.byDecide} theorem(s) closing by decide`)
  console.log('  Correct `def settledHere` in each file above, or add the theorem the count was counting on.')
  process.exit(1)
}

const lean = `-- GENERATED by scripts/settled.ts — do not edit. Regenerate with \`npm run settled\`.
-- title: What each file says it settles, checked against what it does
-- wing: the record
-- prior_art: unclassified
-- prior_art_domain: elementary arithmetic and list operations on naturals — zip, sum by fold, deduplication,
--   and comparison. None of it is this deposit's and none of it is new.
-- prior_art_note: THE ARITHMETIC IS NAMED, NOT CLAIMED. What is this deposit's is only the subject: that
--   these particular files' self-declared counts agree with their own contents. The statement is about this
--   tree and asserts nothing about anybody else's work.
-- prior_art_search: not performed — the arithmetic is named above rather than searched for, and the subject
--   is this deposit's own sources, where there is nothing to search.
-- prior_art_pool: bounded
-- prior_art_own: the agreement between each file's declared count and its measured contents
-- Author: Tsvetan Rouschev · License: CC BY-NC-ND 4.0
--
-- ${rows.length} source files declare \`settledHere\` — the count of declarations that file closes by exhaustion.
-- Until this file existed each was followed by \`theorem …_settles_its_range : settledHere = N := rfl\`, a
-- constant compared to itself. seal-lean refused to seal every one of them as "a declaration, not algebra",
-- so the numbers a reader quotes were hand-maintained with nothing checking them and a tautology standing
-- where the check should have been.
--
-- THE TWO COLUMNS COME FROM INDEPENDENT READS OF THE SAME FILES. \`declared\` names the imported
-- \`settledHere\` defs directly, so Lean reads each hand-set constant out of its own source; \`measured\` is
-- written here by the generator from a parse of the \`by decide\` theorems. Nothing in this file can make them
-- agree — adding a \`by decide\` theorem to any of them without bumping its count stops this file compiling.
--
-- WHAT THIS DOES NOT SAY: nothing here judges whether a count is the RIGHT measure of what a file settles,
-- and nothing here checks the theorems themselves. It checks that a file's own declaration about itself
-- matches its own contents. No axioms, no Mathlib, no sorry.
${rows.map((r) => `import ${r.mod}`).join('\n')}

namespace Settled

def files    : List String := ${L(rows.map((r) => JSON.stringify(r.file)))}
def declared : List Nat := ${L(rows.map((r) => `${r.ns}.settledHere`))}

-- measured by scripts/settled.ts from the tree: \`by decide\` theorems, then all theorems, per file
def measured  : List Nat := ${L(rows.map((r) => r.byDecide))}
def theorems  : List Nat := ${L(rows.map((r) => r.theorems))}
def byRfl     : List Nat := ${L(rows.map((r) => r.byRfl))}
def byOther   : List Nat := ${L(rows.map((r) => r.byOther))}

-- ── 1 · EVERY FILE SETTLES EXACTLY WHAT IT DECLARES ───────────────────────────────────────────────────────
-- The drift check, row by row. The left side is the constant in the source file; the right side is the count
-- of its exhaustive theorems. This is the theorem the fifteen tautologies were standing in for.
theorem every_file_settles_exactly_what_it_declares :
  (declared.zip measured).all (fun p => p.1 == p.2)
  ∧ declared.length == measured.length
  ∧ declared.length == files.length
  ∧ declared.length == ${rows.length} := by decide

-- ── 2 · AND NO FILE DECLARES MORE THAN IT HOLDS ───────────────────────────────────────────────────────────
-- The exhaustive theorems are a SUBSET of the theorems, so the declared count is bounded above by the total
-- and the difference is the declarations closing some other way. A count exceeding the file's own theorems
-- would be impossible rather than merely wrong, and that direction is now decided too.
theorem no_file_declares_more_than_it_holds :
  (declared.zip theorems).all (fun p => p.1 ≤ p.2)
  ∧ (measured.zip theorems).all (fun p => p.1 ≤ p.2) := by decide

-- ── 3 · THE PARTS SUM TO THE WHOLE, AND EACH PART IS RECOVERABLE ──────────────────────────────────────────
-- Conservation with its inverse: the declared counts add to the same total the measured ones do, and removing
-- any one file's count leaves exactly the rest — so no row can be quietly absorbed into another.
theorem the_parts_sum_to_the_whole_and_each_part_is_recoverable :
  declared.foldl (· + ·) 0 == measured.foldl (· + ·) 0
  ∧ declared.foldl (· + ·) 0 == ${total}
  ∧ (List.range declared.length).all (fun i =>
      declared.foldl (· + ·) 0 - declared.getD i 0
        == ((List.range declared.length).filter (fun j => j != i)).foldl
             (fun a j => a + declared.getD j 0) 0) := by decide

-- ── 4 · NO FILE SETTLES NOTHING ───────────────────────────────────────────────────────────────────────────
-- A file declaring zero would pass row 1 by holding no exhaustive theorem at all, which is agreement without
-- content. Every count is positive, so every row above is a claim about something.
theorem no_file_settles_nothing :
  declared.all (fun n => 0 < n) ∧ measured.all (fun n => 0 < n) := by decide

-- ── 5 · THE CONTROL: THE AGREEMENT IS NOT ONE NUMBER REPEATED ─────────────────────────────────────────────
-- THE THEOREM THAT STOPS ROW 1 FROM BEING VACUOUS. Row-wise equality between two lists would hold trivially
-- if every entry were the same value, so it is decided here that the counts genuinely differ: the distinct
-- values number more than one, and the extremes are far apart. Without this, a generator that emitted a
-- constant column would read as green.
theorem the_counts_are_not_one_number_repeated :
  1 < declared.eraseDups.length
  ∧ declared.eraseDups.length == ${new Set(rows.map((r) => r.declared)).size}
  ∧ (declared.foldl (fun a b => if a < b then b else a) 0)
      > (declared.foldl (fun a b => if b < a then b else a) 1000) := by decide

-- ── 6 · AND EACH FILE IS COUNTED ONCE ─────────────────────────────────────────────────────────────────────
-- Two rows for one file would double it in the total while every row still agreed with itself. The names are
-- distinct, so the sum above is over fifteen files and not fourteen files and a repeat.
theorem each_file_is_counted_once :
  files.eraseDups.length == files.length
  ∧ files.length == ${rows.length} := by decide

-- ── 7 · THE TWO PROOF STYLES PARTITION THE THEOREMS, AND NEITHER IS A DECLARATION ─────────────────────────
-- What is not closed by exhaustion is closed by a tactic block over a ∀ — a THEOREM, proved for every value.
-- The two counts add to the file's total and neither overlaps the other, so "not by decide" and "a declaration"
-- are different things and the difference is decided here rather than assumed.
theorem the_two_proof_styles_partition_the_theorems :
  ((measured.zip byOther).map (fun p => p.1 + p.2)) == theorems
  ∧ measured.foldl (· + ·) 0 + byOther.foldl (· + ·) 0 == theorems.foldl (· + ·) 0
  ∧ (measured.zip theorems).all (fun p => p.1 ≤ p.2) := by decide

-- ── 8 · AND NOT ONE DECLARATION IN THESE FILES CLOSES BY rfl ───────────────────────────────────────────────
-- THE THEOREM THAT FALSIFIES A SENTENCE THIS DEPOSIT WAS PUBLISHING. scripts/pages.ts wrote, on the README
-- and the index, "the remaining N close by rfl and are declarations", computing N as the total less the
-- by-decide count — which treats every proof that is not an exhaustion as an rfl declaration. They are not:
-- they are ∀-quantified theorems. Among the ${rows.length} that declare a count the rfl total is zero, so the
-- sentence named a population that does not exist — every genuine rfl declaration that used to live in them
-- was a \`settledHere = N\` tautology, and each one is gone. What that
-- subtraction actually counts is byOther, and THAT is the conjunct below: the quantity pages.ts labelled rfl
-- equals the ∀-proved theorems at every row, so the label was wrong about every one of them.
theorem no_declaration_in_these_files_closes_by_rfl :
  byRfl.all (fun n => n == 0)
  ∧ byRfl.foldl (· + ·) 0 == 0
  ∧ ((theorems.zip measured).map (fun p => p.1 - p.2)) == byOther := by decide

end Settled
`

// CHECK BY DEFAULT, WRITE ONLY WHEN ASKED — and the check FAILS on a difference rather than printing one.
// scripts/coils.ts, the other generator of a Lean file, prints without --emit and exits 0, so coils.lean can
// drift from its generator while the chain reads green. That is the defect this deposit has already recorded
// as "a derived file whose generator is in no chain step drifts and ships", and a generator that is in the
// chain but declines to fail is the same defect one layer in. This one is in `gates` and it fails.
const EMIT = process.argv.includes('--emit')
const onDisk = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
if (!EMIT && onDisk !== lean) {
  console.log(`✗ settled: ${OUT} is not what the tree generates — run \`npm run settled:emit\``)
  if (!onDisk) console.log('    the file is missing entirely')
  else {
    const a = onDisk.split('\n'), b = lean.split('\n')
    for (let i = 0; i < Math.max(a.length, b.length); i++) {
      if (a[i] !== b[i]) { console.log(`    first difference at line ${i + 1}:\n      on disk:    ${a[i] ?? '(end of file)'}\n      generated:  ${b[i] ?? '(end of file)'}`); break }
    }
  }
  process.exit(1)
}
if (EMIT) writeFileSync(OUT, lean)
console.log(`✓ settled: ${rows.length} file(s) declare a count, ${total} settled in total${EMIT ? ` → ${OUT}` : ' — the generated file matches the tree'}`)
for (const r of rows) console.log(`    ${r.file.padEnd(18)} declared ${String(r.declared).padStart(3)} · by decide ${String(r.byDecide).padStart(3)} · theorems ${String(r.theorems).padStart(3)}${r.declared === r.byDecide ? '' : '   ✗ DRIFT'}`)

