// EMIT — write the mechanically translated claims as a Lean file, then let the gates judge it.
//
// Nothing here decides whether a theorem is true. It renders the claim the ledger already states, in Lean,
// and hands it to the kernel. Four things must hold before anything is sealed, and they are checked by the
// tools that own them rather than re-implemented here: it compiles, every theorem is axiom-free, the
// ledger's own test still computes true at the same claim, and the emitted statement contains no construct
// the translator refuses. A claim that fails any of them is left in the queue with its reason.
import { readFileSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { queue } from './index.ts'
import { translate, PREAMBLE, importsFor } from './translate.ts'

const OUT = 'src/proof/mechanical.lean'

export function emit(): { written: number; skipped: number; file: string } {
  const q = queue()
  const rendered = q.map((p) => ({ p, t: translate(p.body) })).filter((x) => x.t.ok) as
    { p: { key: string; name: string }; t: { ok: true; lean: string } }[]

  // IMPORT THE PORT, NEVER RESTATE IT. A rendered claim that needs toUuid uses address.lean's own definition,
  // which is pinned to the shipped implementation by its agreement theorems. Copying that definition into the
  // generated file would create a second toUuid to keep in step, which is the shape of every drift here.
  const needed = [...new Set(rendered.flatMap((x) => importsFor(x.t.lean)))].sort()
  // FRONTMATTER, because the page reads it. Regenerating this file used to strip the `-- title:` / `-- wing:`
  // block that every hand-written proof carries, so the one file produced by a machine was the one file the
  // documentation could not describe. A generator that cannot introduce its own output is not finished.
  let body = needed.map((m) => `import ${m}\n`).join('') + `set_option maxRecDepth 400000\n`
  body += `-- title: Mechanically translated\n-- wing: the machine\n-- prior_art: unclassified\n`
  body += `-- Generated by src/prove/emit.ts from the ledger's own tests — do not hand-edit; re-run the prover.\n`
  body += `--\n`
  body += `-- Each theorem below is a claim the ledger already asserts, rendered into Lean by a whitelist\n`
  body += `-- translation of the deposit's test vocabulary. The rendering is mechanical: no construct outside the\n`
  body += `-- vocabulary is translated, because a guess would produce a theorem that compiles and states something\n`
  body += `-- else. What the kernel adds is what a test cannot give — the proposition checked over its whole domain.\n\n`
  body += `namespace Mechanical\n\n${PREAMBLE}\n\n`
  for (const { p, t } of rendered) {
    body += `-- ${p.name.replace(/\n/g, ' ').slice(0, 110)}\n`
    body += `theorem ${p.key} : ${t.lean} := by decide\n\n`
  }
  body += `end Mechanical\n`
  writeFileSync(OUT, body)

  // QUARANTINE — a translator bug must never redden the build. Translation is a whitelist, not a proof that
  // the output type-checks: a method chain rendered without brackets parsed as something else entirely and
  // took the whole file down with an error that pointed nowhere near the cause. So the file is compiled here,
  // and any theorem the kernel will not accept is REMOVED and reported as a refusal carrying the kernel's own
  // words. A claim that cannot be rendered is not a failure of the build; it is the work list. What must never
  // happen is the two being confused, because then a bad rendering looks like a broken deposit.
  const compiles = (): string | null => {
    try { execSync('cd src/proof && LEAN_PATH=. lean mechanical.lean', { encoding: 'utf8', stdio: 'pipe' }); return null }
    catch (e) { return String((e as { stdout?: string; stderr?: string }).stdout ?? '') + String((e as { stderr?: string }).stderr ?? '') }
  }
  const quarantined: string[] = []
  for (let pass = 0; pass < 12; pass++) {
    const err = compiles()
    if (!err) break
    // A MISSING MODULE IS NOT A BAD THEOREM. `import Address` failing on line 1 yields no theorem position, so
    // the attribution below finds nothing and the bisection starts deleting — removing innocent theorems and
    // reporting them as kernel-rejected. The failure is environmental (the .olean is not built yet); say so
    // and stop, rather than mutilating the file to make a build error go away.
    if (/unknown module prefix|no such file or directory.*olean|No directory .* or file .*\.olean/i.test(err)) {
      console.error('✗ emit: a module this file imports is not built — run `node scripts/lean.ts` first so the .oleans exist.')
      console.error('  ' + err.split('\n').filter(Boolean).slice(0, 2).join('\n  '))
      console.error('  Nothing was quarantined: this is not a theorem failing, it is the import path.')
      process.exit(1)
    }
    const lines = [...err.matchAll(/mechanical\.lean:(\d+):/g)].map((m) => Number(m[1]))
    const src = readFileSync(OUT, 'utf8').split('\n')
    const bad = new Set<string>()
    // when the kernel reported positions we can name the offenders directly; otherwise bisect below
    for (const ln of lines) {
      for (let i = Math.min(ln, src.length) - 1; i >= 0; i--) {
        const m = src[i].match(/^theorem ([A-Za-z_0-9]+) :/)
        if (m) { bad.add(m[1]); break }
      }
    }
    // NO LINE NUMBER, NO CULPRIT — bisect. A stack overflow aborts the kernel before it can say WHERE, so the
    // error carries no position at all and the loop above has nothing to remove. Halving the file finds the
    // offender in a handful of compiles instead of one per theorem, and it is the only method that works when
    // the failure is the compiler dying rather than reporting.
    if (!lines.length || !bad.size) {
      const all = readFileSync(OUT, 'utf8')
      const head = all.slice(0, all.indexOf('theorem '))
      const blocks = all.slice(all.indexOf('theorem ')).split(/\n\n(?=(?:-- [^\n]*\n)?theorem )/)
      const tail = blocks.length ? '' : ''
      let lo = 0, hi = blocks.length
      const tryRange = (a: number, b: number) => {
        writeFileSync(OUT, head + blocks.slice(a, b).join('\n\n') + '\n' + tail)
        return compiles() === null
      }
      while (hi - lo > 1) {
        const mid = Math.floor((lo + hi) / 2)
        if (!tryRange(lo, mid)) { hi = mid } else { lo = mid }
      }
      const culprit = blocks[lo]?.match(/^(?:-- [^\n]*\n)?theorem ([A-Za-z_0-9]+)/)?.[1]
      blocks.splice(lo, 1)
      writeFileSync(OUT, head + blocks.join('\n\n') + '\n' + tail)
      if (culprit) quarantined.push(culprit + ' (kernel aborted — no position reported; found by bisection)')
      continue
    }
    let out = readFileSync(OUT, 'utf8')
    for (const name of bad) {
      out = out.replace(new RegExp('(?:^-- [^\\n]*\\n)?^theorem ' + name + ' :[\\s\\S]*?:= by decide\\n\\n', 'm'), '')
      quarantined.push(name)
    }
    writeFileSync(OUT, out)
  }
  if (quarantined.length) console.log('  quarantined ' + quarantined.length + ' theorem(s) the kernel would not accept: ' + quarantined.slice(0, 6).join(', ') + (quarantined.length > 6 ? ' …' : ''))
  return { written: rendered.length, skipped: q.length - rendered.length, file: OUT }
}

if (process.argv[1]?.includes('emit')) {
  const r = emit()
  console.log(`✓ ${r.file} — ${r.written} claims rendered, ${r.skipped} left in the queue with a reason`)
}
