// EMIT — write the mechanically translated claims as a Lean file, then let the gates judge it.
//
// Nothing here decides whether a theorem is true. It renders the claim the ledger already states, in Lean,
// and hands it to the kernel. Four things must hold before anything is sealed, and they are checked by the
// tools that own them rather than re-implemented here: it compiles, every theorem is axiom-free, the
// ledger's own test still computes true at the same claim, and the emitted statement contains no construct
// the translator refuses. A claim that fails any of them is left in the queue with its reason.
import { readFileSync, writeFileSync } from 'node:fs'
import { queue } from './index.ts'
import { translate, PREAMBLE } from './translate.ts'

const OUT = 'src/proof/mechanical.lean'

export function emit(): { written: number; skipped: number; file: string } {
  const q = queue()
  const rendered = q.map((p) => ({ p, t: translate(p.body) })).filter((x) => x.t.ok) as
    { p: { key: string; name: string }; t: { ok: true; lean: string } }[]

  let body = `set_option maxRecDepth 400000\n`
  body += `-- Generated by src/prove/emit.ts from the ledger's own tests — do not hand-edit; re-run the prover.\n`
  body += `--\n`
  body += `-- Each theorem below is a claim the ledger already asserts, rendered into Lean by a whitelist\n`
  body += `-- translation of the deposit's test vocabulary. The rendering is mechanical: no construct outside the\n`
  body += `-- vocabulary is translated, because a guess would produce a theorem that compiles and states something\n`
  body += `-- else. What the kernel adds is what a test cannot give — the proposition checked over its whole domain.\n\n`
  body += `namespace Mechanical\n\n${PREAMBLE}\n\n`
  for (const { p, t } of rendered) {
    body += `-- ${p.name.replace(/\n/g, ' ').slice(0, 110)}\n`
    body += `theorem ${p.key} : ${t.lean} := by decide\n\n`
  }
  body += `end Mechanical\n`
  writeFileSync(OUT, body)
  return { written: rendered.length, skipped: q.length - rendered.length, file: OUT }
}

if (process.argv[1]?.includes('emit')) {
  const r = emit()
  console.log(`✓ ${r.file} — ${r.written} claims rendered, ${r.skipped} left in the queue with a reason`)
}
